import type { LevelPack } from '../../../game/types'

export const earlyRepublicLevel: LevelPack = {
  id: 'early-republic',
  title: '沪上初潮',
  theme: 'early-republic',
  eraLabel: '民国初年',
  year: 1912,
  regionLabel: '上海',
  startNodeId: 'scene_station',
  correctAnswers: {
    period: '民国初年',
    region: '上海',
    identities: ['student', 'clerk', 'returnee', 'shop_assistant'],
  },
  sources: [
    {
      id: 'er_s1',
      title: '申报·民国元年报道',
      citation: '《申报》1912年前后期相关报道',
      factType: 'historical',
      summary: '民国初年上海仍保留大量前清习惯，同时出现新机构、新报刊与新称谓。',
    },
    {
      id: 'er_s2',
      title: '上海公共租界与华界行政研究',
      citation: '学界关于民国初年上海华界与租界治理的研究',
      factType: 'inference',
      summary: '同一城市并存不同治理规则，身份与证件在不同区域效力不同。',
    },
    {
      id: 'er_s3',
      title: '民国初年货币与票据',
      citation: '民国初年银元、铜元与票号票据流通资料',
      factType: 'historical',
      summary: '银元、铜元并用，新旧票据体系仍在过渡。',
    },
  ],
  identities: [
    {
      id: 'student',
      label: '携带介绍信的学生',
      description: '你持有一封介绍信，但不确定收信人是否还在原址。',
      startingStats: { stamina: 65, wealth: 18, exposure: 14 },
      flags: ['has_letter'],
    },
    {
      id: 'clerk',
      label: '报馆或商铺伙计',
      description: '你熟悉城市信息渠道，却缺少正式身份证明。',
      startingStats: { stamina: 60, wealth: 20, exposure: 16 },
      flags: ['knows_press'],
    },
    {
      id: 'returnee',
      label: '从外埠来沪的客人',
      description: '你带有少量银元，但不清楚新政府规则在本地如何执行。',
      startingStats: { stamina: 70, wealth: 28, exposure: 18 },
      flags: ['has_silver'],
    },
    {
      id: 'shop_assistant',
      label: '南货店学徒',
      description: '你识得商行规矩，需要尽快找到旧东或新雇主。',
      startingStats: { stamina: 62, wealth: 15, exposure: 12 },
      flags: ['knows_shop'],
    },
  ],
  evidence: [
    {
      id: 'er_e1',
      title: '民国纪年',
      description: '报纸与告示并用“民国元年”和旧历，显示新旧交替。',
      category: '文字与文书',
      strength: 'strong',
      sourceId: 'er_s1',
      hints: { period: '民国初年' },
    },
    {
      id: 'er_e2',
      title: '银元与铜元',
      description: '交易中使用银元、铜元，票号票据尚未完全统一。',
      category: '货币与交易',
      strength: 'strong',
      sourceId: 'er_s3',
      hints: { period: '民国初年' },
    },
    {
      id: 'er_e3',
      title: '电车与洋行',
      description: '街上有电车、洋行与中文报刊，符合近代上海特征。',
      category: '城市与建筑',
      strength: 'strong',
      sourceId: 'er_s2',
      hints: { region: '上海' },
    },
    {
      id: 'er_e4',
      title: '剪辫与旧习',
      description: '有人已剪辫，仍有人保留前清发式，制度变化在本地并不一致。',
      category: '社会习俗',
      strength: 'weak',
      sourceId: 'er_s1',
      hints: { period: '民国初年' },
    },
    {
      id: 'er_e5',
      title: '租界告示',
      description: '华界与租界告示并用不同规则，容易误以为是完全不同的国家。',
      category: '官制与法律',
      strength: 'misleading',
      sourceId: 'er_s2',
      hints: { region: '上海' },
    },
    {
      id: 'er_e6',
      title: '申报馆',
      description: '申报馆仍每日刊行，城市信息传播极快。',
      category: '交通与通信',
      strength: 'strong',
      sourceId: 'er_s1',
      hints: { region: '上海' },
    },
  ],
  nodes: [
    {
      id: 'scene_station',
      type: 'scene',
      title: '到站',
      background: 'early-republic-station',
      text: '你在嘈杂的车站醒来。报童叫卖“民国元年”的报纸，街上有电车和洋行招牌。你不记得自己为何在此，但身上的介绍信或银元或许还能派上用场。',
      revealEvidence: ['er_e1', 'er_e3'],
      choices: [
        {
          id: 'c_read_paper',
          text: '买一份报纸，先看日期与新闻',
          next: 'scene_street',
          effects: [
            { type: 'modifyStat', stat: 'wealth', delta: -3 },
            { type: 'revealEvidence', evidenceId: 'er_e6' },
          ],
        },
        {
          id: 'c_check_money',
          text: '检查随身银元与票据',
          next: 'scene_street',
          condition: { type: 'flag', flag: 'has_silver' },
          effects: [{ type: 'revealEvidence', evidenceId: 'er_e2' }],
        },
        {
          id: 'c_check_letter',
          text: '检查介绍信与收信地址',
          next: 'scene_street',
          condition: { type: 'flag', flag: 'has_letter' },
        },
        {
          id: 'c_walk_direct',
          text: '直接沿街前行，随机应变',
          next: 'scene_street',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 5 }],
        },
      ],
    },
    {
      id: 'scene_street',
      type: 'scene',
      title: '街面',
      background: 'early-republic-street',
      text: '街面新旧并存：有人剪辫，有人仍保留旧发式；华界与租界告示并用不同规则。现代化器物已经出现，但并不意味着现代社会规则已经完整建立。',
      revealEvidence: ['er_e4', 'er_e5'],
      choices: [
        {
          id: 'c_find_lodging',
          text: '找客栈住下',
          next: 'scene_lodging',
          effects: [
            { type: 'modifyStat', stat: 'wealth', delta: -6 },
            { type: 'modifyStat', stat: 'stamina', delta: 8 },
          ],
        },
        {
          id: 'c_find_press',
          text: '去报馆打听消息',
          next: 'scene_press',
          condition: { type: 'flag', flag: 'knows_press' },
        },
      ],
    },
    {
      id: 'scene_lodging',
      type: 'scene',
      title: '客栈',
      background: 'early-republic-inn',
      speaker: '掌柜',
      text: '掌柜问你的来历与证件。民国初年，上海仍看重介绍信、铺保和旧有关系网。新政府的名义并不自动等于新的生存规则。',
      revealEvidence: ['er_e2'],
      choices: [
        {
          id: 'c_lodge_rest',
          text: '先住下，整理线索',
          next: 'scene_hypothesis',
        },
        {
          id: 'c_deliver_letter',
          text: '按介绍信地址送信',
          next: 'scene_letter',
          condition: { type: 'flag', flag: 'has_letter' },
        },
      ],
    },
    {
      id: 'scene_press',
      type: 'scene',
      title: '报馆',
      background: 'early-republic-press',
      text: '报馆里有人讨论“共和”与“剪辫”，也有人仍用旧称。你能感到：国家层面的变化已经到来，但城市日常生活仍在过渡。',
      choices: [
        {
          id: 'c_press_done',
          text: '带着消息回客栈整理',
          next: 'scene_hypothesis',
        },
      ],
    },
    {
      id: 'scene_letter',
      type: 'scene',
      title: '送信',
      background: 'early-republic-street',
      text: '收信人仍在，但态度谨慎。他愿意为你提供短期落脚，却提醒你不要在外随意谈论“旧制已废”——本地执行并不一致。',
      choices: [
        {
          id: 'c_letter_done',
          text: '返回整理判断',
          next: 'scene_hypothesis',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: -6 }],
        },
      ],
    },
    {
      id: 'scene_hypothesis',
      type: 'scene',
      title: '整理判断',
      background: 'early-republic-inn',
      text: '民国纪年、银元、电车和申报馆共同指向一个近代城市。若你把“有电车”误判为“已是完全现代社会”，接下来很可能在证件和称谓上出错。',
      choices: [
        {
          id: 'c_to_decision',
          text: '决定下一步行动',
          next: 'scene_decision',
        },
      ],
    },
    {
      id: 'scene_decision',
      type: 'scene',
      title: '行动抉择',
      background: 'early-republic-street',
      text: '你可以凭介绍信或铺保留在上海，也可以趁夜转移。若你误判时代，把民国初年当作完全现代秩序，使用不合时宜的说法会立刻暴露。',
      choices: [
        {
          id: 'c_stay_shanghai',
          text: '留在上海，按本地规矩找担保',
          next: 'scene_stay',
        },
        {
          id: 'c_claim_modern',
          text: '以“新国家公民”自居，要求平等对待',
          next: 'scene_modern_claim',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 10 }],
        },
        {
          id: 'c_leave_shanghai',
          text: '趁夜离开城区',
          next: 'scene_leave',
          effects: [{ type: 'modifyStat', stat: 'stamina', delta: -12 }],
        },
      ],
    },
    {
      id: 'scene_modern_claim',
      type: 'scene',
      title: '错位自称',
      background: 'early-republic-street',
      text: '你的说法过于超前。民国初年的上海确实在变化，但铺保、介绍信和旧有关系网仍未退场。',
      choices: [
        {
          id: 'c_modern_fail',
          text: '坚持说法',
          next: 'ending_exposed',
          condition: { type: 'hypothesisMismatch', field: 'period', value: '民国初年' },
        },
        {
          id: 'c_modern_recover',
          text: '改口称外埠来沪客人',
          next: 'scene_stay',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 8 }],
        },
      ],
    },
    {
      id: 'scene_stay',
      type: 'scene',
      title: '留沪',
      background: 'early-republic-street',
      text: '你通过介绍信或商铺关系找到短期担保。若你对“民国初年上海”的判断正确，留下比盲目离开更可行。',
      choices: [
        {
          id: 'c_stay_success',
          text: '接受担保，在上海立足',
          next: 'ending_success_stay',
          condition: { type: 'hypothesisMatch', field: 'period', value: '民国初年' },
        },
        {
          id: 'c_stay_partial',
          text: '勉强留下',
          next: 'ending_partial_stay',
        },
      ],
    },
    {
      id: 'scene_leave',
      type: 'scene',
      title: '离城',
      background: 'early-republic-station',
      text: '你离开上海，躲过了证件与铺保的压力，却必须在别处自行解决食宿。',
      choices: [
        {
          id: 'c_leave_end',
          text: '继续赶路',
          next: 'ending_partial_leave',
        },
      ],
    },
    {
      id: 'ending_success_stay',
      type: 'ending',
      title: '沪上立足',
      outcome: 'success',
      text: '你在上海获得短期担保，找到了继续生存的位置。新旧交替的城市里，理解规则比口号更重要。',
      unlockSources: ['er_s1', 'er_s2'],
    },
    {
      id: 'ending_partial_stay',
      type: 'ending',
      title: '悬居沪上',
      outcome: 'partial',
      text: '你留在上海，却始终没有完全融入。你活了下来，但随时可能被新的查验打乱安排。',
      unlockSources: ['er_s3'],
    },
    {
      id: 'ending_partial_leave',
      type: 'ending',
      title: '夜离上海',
      outcome: 'partial',
      text: '你离开了上海，躲过了证件压力，却仍未找到真正安身之处。',
      unlockSources: ['er_s1'],
    },
    {
      id: 'ending_exposed',
      type: 'ending',
      title: '来历可疑',
      outcome: 'failure',
      text: '你的说法与本地实际规则严重不符。在民国初年的上海，被怀疑往往意味着失去担保与落脚处。',
      unlockSources: ['er_s2'],
    },
    {
      id: 'ending_exhaustion',
      type: 'ending',
      title: '力竭',
      outcome: 'failure',
      text: '你在电车和洋行之间耗尽最后一丝体力，再未能撑到下一个可容身之处。',
    },
    {
      id: 'ending_critical_injury',
      type: 'ending',
      title: '伤病',
      outcome: 'failure',
      text: '伤病让你无法继续在上海行动。近代城市不会为无法行动的人停留。',
    },
    {
      id: 'ending_exposed_stat',
      type: 'ending',
      title: '嫌疑',
      outcome: 'failure',
      text: '关于你的议论已经扩散，客栈与商铺都不再欢迎你。',
    },
  ],
}
