import type { LevelPack } from '../../../game/types'

export const earlyRepublicLevel: LevelPack = {
  id: 'early-republic',
  title: '沪上初潮',
  theme: 'early-republic',
  eraLabel: '民国初年',
  year: 1912,
  regionLabel: '上海',
  oneLiner:
    '1912年，一座华洋杂处的通商口岸，一个缺少统一证件的人，必须在铺保与新旧规矩之间找到落脚处。',
  coreCrisis:
    '新政府名义已立，但铺保、介绍信与地方查验仍按旧例或洋界各自规矩执行；证件效力在华界与外人街区并不一致，短时间内找不到担保就无法合法住下。',
  historicalBackground:
    '1912年（民国元年），上海刚经历政权更替，华界与租界并存、各自为政。车站、客栈与商铺仍看重铺保和介绍信，不同街区对证件的要求并不统一；银元铜元并用，报刊与电车已普及，但社会规则远未同步更新。本关核心危机——证件与铺保不统一——正是这一过渡期的日常困境。',
  crossing: {
    background: 'early-republic-station',
    leadText:
      '穿越失败。汽笛与报童的嗓子同时炸开，纸墨与机油味道冲进肺里，像被一列尚未停稳的车抛到月台上。',
    sceneText:
      '车站外电车铃响，华洋街面各行其是。客栈柜台要看介绍与铺保，不同街区口径却不一致。你还对不上这是哪一年的口岸，只明白：证件若对不上眼下的规矩，今夜仍可能无家可归。',
  },
  startNodeId: 'scene_station',
  correctAnswers: {
    period: '民国初年',
    region: '上海',
    identities: ['student', 'clerk', 'returnee', 'shop_assistant'],
  },
  sources: [
    {
      id: 'er_s1',
      title: '《申报》辛亥后城市社会报道辑要',
      citation: '《申报》1912年1—3月城市社会新闻与告示',
      factType: 'historical',
      summary:
        '政权更替后，城市报刊仍每日刊行；新旧纪年、称谓与告示并用，地方秩序处于过渡。',
      grade: 'A',
      author: '申报馆',
      createdOrPublished: '1912年1—3月',
      locator: '上海图书馆近代报刊全文数据库，《申报》1912年相关刊期',
      supports:
        '新式纪年与旧历并用、剪辫与旧发式并存、城市信息传播迅速',
      cannotProve:
        '某一具体人物的行踪、某家商铺铺保文书的确切格式与签发时点',
    },
    {
      id: 'er_s2',
      title: '民国初年上海华界与租界行政比较研究',
      citation: '学界关于1912年前后上海华界、公共租界治理规则差异的论文与专著',
      factType: 'inference',
      summary:
        '同一城市内华界与租界适用不同办事程序与告示体系，外人街区规则不能套用于华界居民。',
      grade: 'B',
      author: '近现代城市史研究综合',
      createdOrPublished: '20世纪末—21世纪初研究论著',
      locator: '学术期刊与专著中关于1912年上海华洋分区治理的章节',
      supports:
        '华界与租界告示并用不同规则、证件效力因区域而异',
      cannotProve:
        '某年某月某日某公所的具体办事流程、个别领事馆的登记细节',
    },
    {
      id: 'er_s3',
      title: '民国初年银元铜元与票号票据流通',
      citation: '民国初年货币制度与地方商业票据档案及研究',
      factType: 'historical',
      summary:
        '银元、铜元仍是主要流通货币，票号票据与新旧计价方式并存，尚未完全统一。',
      grade: 'A',
      author: '民国财政史与商业史档案整理',
      createdOrPublished: '1912年前后档案及后世整理本',
      locator: '中国第二历史档案馆及民国财政史研究相关卷册',
      supports:
        '银元铜元并用、票号票据仍在流通、货币体系处于过渡',
      cannotProve:
        '本局某一具体交易的确切物价、某张票据的真伪与签发铺号',
    },
  ],
  identities: [
    {
      id: 'student',
      label: '携带介绍信的学生',
      description: '你持有一封介绍信，但不确定收信人是否还在原址。',
      background: {
        livelihood: '受新式教育的学生，凭介绍信来城寻人求学或谋事',
        socialPosition: '受教育青年，处于引荐关系链条末端，无独立经济来源',
        affiliation: '依附学校、导师或收信人的引荐网络',
        rightsAndLimits:
          '可凭介绍信短期求助，但无铺保则无法在华界长期合法住下',
        exposureReason:
          '介绍信地址可能失效；若言谈过分激进或不合本地分寸，易被视为来历不明',
      },
      sourceIds: ['er_s1', 'er_s2'],
      startingStats: { stamina: 65, wealth: 18, exposure: 14 },
      flags: ['has_letter'],
    },
    {
      id: 'clerk',
      label: '报馆或商铺伙计',
      description: '你熟悉城市信息渠道，却缺少正式身份证明。',
      background: {
        livelihood: '在报馆或商铺做校对、跑街、抄录，靠消息与文字糊口',
        socialPosition: '城市信息下层从业者，识得门路但无体面身份',
        affiliation: '报馆或商铺雇工圈，与行业铺保体系若即若离',
        rightsAndLimits:
          '可进报馆打听消息，但无雇主铺保时仍被视为流散雇工',
        exposureReason:
          '长期无铺保、无固定雇主，客栈与公所查验时首当其冲',
      },
      sourceIds: ['er_s1', 'er_s3'],
      startingStats: { stamina: 60, wealth: 20, exposure: 16 },
      flags: ['knows_press'],
    },
    {
      id: 'returnee',
      label: '从外埠来城的客人',
      description: '你带有少量银元，但不清楚新政府规则在本地如何执行。',
      background: {
        livelihood: '外埠来客，或投亲或经商，随身携带现洋与少量票据',
        socialPosition: '过路客商或投亲者，本地无固定依附',
        affiliation: '原籍关系远，在华界无铺保、无行业担保',
        rightsAndLimits:
          '可短期花钱住店，但长期居留必须找到保人或商铺出具铺保',
        exposureReason:
          '不熟悉华界与外人街区的分界规矩，易按外埠或洋界经验误办手续',
      },
      sourceIds: ['er_s2', 'er_s3'],
      startingStats: { stamina: 70, wealth: 28, exposure: 18 },
      flags: ['has_silver'],
    },
    {
      id: 'shop_assistant',
      label: '南货店学徒',
      description: '你识得商行规矩，需要尽快找到旧东或新雇主。',
      background: {
        livelihood: '南货店学徒，熟悉商行铺保、账册与同业规矩',
        socialPosition: '商铺学徒，处于铺保担保链条底端',
        affiliation: '旧东商铺或同业行会，铺保关系是立足关键',
        rightsAndLimits:
          '识得铺保文书格式，可请旧东或新雇主开具；与旧东失联则链条断裂',
        exposureReason:
          '若找不到旧东，铺保缺失会被当作无业流散人员盘查',
      },
      sourceIds: ['er_s1', 'er_s2', 'er_s3'],
      startingStats: { stamina: 62, wealth: 15, exposure: 12 },
      flags: ['knows_shop'],
    },
  ],
  evidence: [
    {
      id: 'er_e1',
      title: '新旧纪年并用',
      description:
        '报纸头版与街面告示同时出现新旧两种纪年写法，显示政权更替尚在本地落地。',
      category: '文字与文书',
      strength: 'strong',
      sourceId: 'er_s1',
      hints: { period: '民国初年' },
    },
    {
      id: 'er_e2',
      title: '银元与铜元',
      description: '交易中使用银元、铜元，票号票据尚未完全统一。',
      category: '货币与交易',
      strength: 'strong',
      sourceId: 'er_s3',
      hints: { period: '民国初年' },
    },
    {
      id: 'er_e3',
      title: '电车与洋行',
      description: '街上有电车、洋行与中文报刊，符合近代通商口岸城市特征。',
      category: '城市与建筑',
      strength: 'strong',
      sourceId: 'er_s2',
      hints: { region: '上海' },
    },
    {
      id: 'er_e4',
      title: '剪辫与旧习',
      description: '有人已剪辫，仍有人保留前清发式，制度变化在本地并不一致。',
      category: '社会习俗',
      strength: 'weak',
      sourceId: 'er_s1',
      hints: { period: '民国初年' },
    },
    {
      id: 'er_e5',
      title: '分区告示差异',
      description:
        '华界公所告示与外人街区工部局告示措辞、印章截然不同，初来者易误以为需按两套"国别"分别办事。',
      category: '官制与法律',
      strength: 'misleading',
      sourceId: 'er_s2',
      hints: { region: '上海' },
    },
    {
      id: 'er_e6',
      title: '大型中文报刊馆',
      description: '本地大型中文报刊仍每日刊行，城市信息传播极快。',
      category: '交通与通信',
      strength: 'strong',
      sourceId: 'er_s1',
      hints: { region: '上海' },
    },
  ],
  nodes: [
    {
      id: 'scene_station',
      type: 'scene',
      title: '到站',
      background: 'early-republic-station',
      text: '你在嘈杂的车站醒来。报童叫卖当日新报纸，头版纪年写法让你一时分不清新旧；街上有电车和洋行招牌。你不记得自己为何在此，但身上的介绍信、零钱或商行记忆或许还能派上用场。',
      revealEvidence: ['er_e1', 'er_e3'],
      choices: [
        {
          id: 'c_read_paper',
          text: '买一份报纸，先看日期与新闻',
          next: 'scene_street',
          strategyTags: ['follow_institution'],
          settlementNote: '你花钱买报，从纪年、称谓与告示里拼凑本地规矩。',
          effects: [
            { type: 'modifyStat', stat: 'wealth', delta: -3 },
            { type: 'revealEvidence', evidenceId: 'er_e6' },
          ],
        },
        {
          id: 'c_check_money',
          text: '检查随身银元与票据',
          next: 'scene_street',
          condition: { type: 'flag', flag: 'has_silver' },
          strategyTags: ['exchange_resources'],
          settlementNote: '你清点现洋与票据，确认自己还能撑过几日的食宿。',
          effects: [{ type: 'revealEvidence', evidenceId: 'er_e2' }],
        },
        {
          id: 'c_check_letter',
          text: '检查介绍信与收信地址',
          next: 'scene_street',
          condition: { type: 'flag', flag: 'has_letter' },
          strategyTags: ['rely_on_relations'],
          settlementNote: '你核对介绍信上的地址与名讳，把引荐关系当作第一条线索。',
        },
        {
          id: 'c_walk_direct',
          text: '直接沿街前行，随机应变',
          next: 'scene_street',
          strategyTags: ['avoid_transfer'],
          settlementNote: '你不作停留，带着未知身份直入街面。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 5 }],
        },
      ],
    },
    {
      id: 'scene_street',
      type: 'scene',
      title: '街面',
      background: 'early-republic-street',
      text: '街面新旧并存：有人剪辫，有人仍保留旧发式。穿过一处路口，你看见两套告示并排张贴——华界公所的朱印告示与外人街区工部局的英文告示各说各话，仿佛两套完全不同的规矩。现代化器物已经出现，但并不意味着办事程序已经统一。',
      revealEvidence: ['er_e4', 'er_e5'],
      choices: [
        {
          id: 'c_find_lodging',
          text: '找客栈住下，先稳住脚跟',
          next: 'scene_lodging',
          strategyTags: ['exchange_resources'],
          settlementNote: '你花钱住店，换来了整理线索的时间。',
          effects: [
            { type: 'modifyStat', stat: 'wealth', delta: -6 },
            { type: 'modifyStat', stat: 'stamina', delta: 8 },
          ],
        },
        {
          id: 'c_find_press',
          text: '去报馆打听消息',
          next: 'scene_jurisdiction',
          condition: { type: 'flag', flag: 'knows_press' },
          strategyTags: ['rely_on_relations'],
          settlementNote: '你从报馆带回华界与外人街区的分工消息，准备按区办事。',
          effects: [
            { type: 'modifyStat', stat: 'stamina', delta: -3 },
            { type: 'modifyStat', stat: 'exposure', delta: -2 },
          ],
        },
        {
          id: 'c_find_shop',
          text: '沿商行招牌寻找旧东铺号',
          next: 'scene_shop_route',
          condition: { type: 'flag', flag: 'knows_shop' },
          strategyTags: ['rely_on_relations', 'labor_trade'],
          settlementNote: '你沿商行招牌寻人，试图接上旧铺保关系。',
        },
      ],
    },
    {
      id: 'scene_lodging',
      type: 'scene',
      title: '客栈',
      background: 'early-republic-inn',
      speaker: '掌柜',
      text: '掌柜问你的来历与证件。他道：近来查得紧，住店要铺保或介绍信，光有银元不够。新政府的名义喊得响，可公所与客栈还是按旧例——没有保人，住不满三天就得挪窝。',
      revealEvidence: ['er_e2'],
      choices: [
        {
          id: 'c_lodge_to_jurisdiction',
          text: '先住下，再去问清办证门路',
          next: 'scene_jurisdiction',
          strategyTags: ['follow_institution'],
          settlementNote: '你暂住客栈，准备按本地程序解决证件问题。',
        },
        {
          id: 'c_deliver_letter',
          text: '按介绍信地址送信',
          next: 'scene_letter',
          condition: { type: 'flag', flag: 'has_letter' },
          strategyTags: ['rely_on_relations'],
          settlementNote: '你决定先走引荐路线，把介绍信送到收信人手中。',
        },
      ],
    },
    {
      id: 'scene_shop_route',
      type: 'scene',
      title: '寻铺',
      background: 'early-republic-street',
      speaker: '旧东柜伙',
      text: '你循着熟悉的招牌找到旧铺，柜伙认出了你。旧东已迁往别处，铺面换了新字号，但同业规矩还在：学徒要有铺保才能在华界客栈长住。柜伙指点你去华界公所登记，或等新东家开具铺保——切忌拿着华界铺保去外人街区工部局，那边不认这套文书。',
      choices: [
        {
          id: 'c_shop_to_jurisdiction',
          text: '按柜伙指点去办铺保',
          next: 'scene_jurisdiction',
          strategyTags: ['rely_on_relations', 'follow_institution'],
          settlementNote: '你接上同业线索，明确铺保只能在华界体系办理。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: -4 }],
        },
        {
          id: 'c_shop_ask_concession',
          text: '既然有两套告示，先去外人街区打听',
          next: 'scene_jurisdiction',
          strategyTags: ['follow_institution'],
          settlementNote: '你被分区告示误导，打算先去外人街区碰运气。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 6 }],
        },
      ],
    },
    {
      id: 'scene_letter',
      type: 'scene',
      title: '送信',
      background: 'early-republic-street',
      text: '收信人仍在，但态度谨慎。他愿意为你提供短期落脚，却提醒你不要在外随意谈论"旧制已废"——本地执行并不一致。他写了一张便条，说可拿去华界公所作引荐，但不能拿去外人街区工部局。',
      choices: [
        {
          id: 'c_letter_to_jurisdiction',
          text: '持便条去办落脚手续',
          next: 'scene_jurisdiction',
          strategyTags: ['rely_on_relations'],
          settlementNote: '送信换来短期庇护与引荐便条，也压低了一点嫌疑。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: -6 }],
        },
      ],
    },
    {
      id: 'scene_jurisdiction',
      type: 'scene',
      title: '分界办事',
      background: 'early-republic-street',
      text: '你站在华界与外人街区的分界附近。一侧是华界公所，收铺保、介绍信与户籍便条；另一侧是工部局与洋行，办的是外人街区的居留与商业登记。方才那两套告示的差异，容易让人以为必须去"外国那边"才能合法住下——但你的身份、铺保与引荐关系，大多只在华界有效。',
      choices: [
        {
          id: 'c_hua_bond',
          text: '在华界公所按铺保旧例登记',
          next: 'scene_hypothesis',
          strategyTags: ['follow_institution', 'rely_on_relations'],
          settlementNote: '你在华界按铺保旧例登记，把立足手续拉回适用的体系。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: -5 }],
        },
        {
          id: 'c_concession_register',
          text: '去外人街区工部局，按洋界告示办居留',
          next: 'scene_concession_fail',
          strategyTags: ['follow_institution'],
          settlementNote: '你被分区告示误导，去了不适用于自己的登记处。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 10 }],
        },
        {
          id: 'c_ask_both_sides',
          text: '先分头问清两边各收什么、不收什么',
          next: 'scene_hypothesis',
          strategyTags: ['rely_on_relations'],
          settlementNote: '你先问清华界与外人街区各自规矩，避免走错门路。',
          effects: [
            { type: 'modifyStat', stat: 'stamina', delta: -5 },
            { type: 'modifyStat', stat: 'exposure', delta: -3 },
          ],
        },
        {
          id: 'c_shop_bond_here',
          text: '请旧东同业开华界铺保，不去工部局',
          next: 'scene_hypothesis',
          condition: { type: 'flag', flag: 'knows_shop' },
          strategyTags: ['rely_on_relations', 'labor_trade'],
          settlementNote: '你坚持走同业铺保，绕开外人街区的误导告示。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: -8 }],
        },
      ],
    },
    {
      id: 'scene_concession_fail',
      type: 'scene',
      title: '错区碰壁',
      background: 'early-republic-street',
      text: '工部局办事员翻看你的文书，摇头道：铺保和华界公所便条在这里不作数。你这才明白，两套告示并不意味着两套身份体系——华界与外人街区各管各的，你的材料得在正确的一边办理。',
      choices: [
        {
          id: 'c_concession_recover',
          text: '赶回华界公所补办',
          next: 'scene_hypothesis',
          strategyTags: ['follow_institution'],
          settlementNote: '你在工部局碰壁后赶回华界，补上正确的登记手续。',
          effects: [
            { type: 'modifyStat', stat: 'stamina', delta: -8 },
            { type: 'modifyStat', stat: 'exposure', delta: 5 },
          ],
        },
        {
          id: 'c_concession_insist',
          text: '坚持洋人街区规矩更高，继续交涉',
          next: 'ending_exposed',
          strategyTags: ['conceal_identity'],
          settlementNote: '你执意按误导认知在工部局纠缠，引来更多怀疑。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 15 }],
        },
      ],
    },
    {
      id: 'scene_hypothesis',
      type: 'scene',
      title: '整理判断',
      background: 'early-republic-inn',
      text: '新旧纪年、银元、电车和报刊共同指向一座近代通商口岸。若你把"有电车"误判为"已是完全现代社会"，或把分区告示误解为"两个国家"，接下来在证件和称谓上还会出错。铺保与介绍信仍是这条街上真实的通行证。',
      choices: [
        {
          id: 'c_to_decision',
          text: '决定下一步行动',
          next: 'scene_decision',
        },
      ],
    },
    {
      id: 'scene_decision',
      type: 'scene',
      title: '行动抉择',
      background: 'early-republic-street',
      text: '你可以凭介绍信或铺保留在城中，也可以趁夜转移。若你误判时代，把政权更替当作完全现代秩序，使用不合时宜的说法会立刻暴露；若你误判地域，把华界与外人街区当作可以随意切换的"外国"，先前办下的手续也会作废。',
      choices: [
        {
          id: 'c_stay_city',
          text: '留在城中，按本地规矩找担保',
          next: 'scene_stay',
          strategyTags: ['rely_on_relations'],
          settlementNote: '你决定留城，按本地规矩找担保。',
        },
        {
          id: 'c_claim_modern',
          text: '以"新国家公民"自居，要求平等对待',
          next: 'scene_modern_claim',
          strategyTags: ['conceal_identity'],
          settlementNote: '你以超前政治自称，测试新秩序是否已在本地落地。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 10 }],
        },
        {
          id: 'c_leave_city',
          text: '趁夜离开城区',
          next: 'scene_leave',
          strategyTags: ['avoid_transfer'],
          settlementNote: '你选择趁夜离城，躲开证件与铺保压力。',
          effects: [{ type: 'modifyStat', stat: 'stamina', delta: -12 }],
        },
      ],
    },
    {
      id: 'scene_modern_claim',
      type: 'scene',
      title: '错位自称',
      background: 'early-republic-street',
      text: '你的说法过于超前。这座通商口岸确实在变化，但铺保、介绍信和旧有关系网仍未退场。掌柜和公所小吏听得懂"共和"，却更认铺保上的朱印。',
      choices: [
        {
          id: 'c_modern_fail',
          text: '坚持说法',
          next: 'ending_exposed',
          strategyTags: ['conceal_identity'],
          settlementNote: '你坚持超前自称，与本地实际规则严重冲突。',
          condition: { type: 'hypothesisMismatch', field: 'period', value: '民国初年' },
        },
        {
          id: 'c_modern_recover',
          text: '改口称外埠来城客人',
          next: 'scene_stay',
          strategyTags: ['conceal_identity'],
          settlementNote: '你改口收敛，用外埠来客身份重新争取担保。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 8 }],
        },
      ],
    },
    {
      id: 'scene_stay',
      type: 'scene',
      title: '留城立足',
      background: 'early-republic-street',
      text: '你通过介绍信、铺保或同业关系找到短期担保。若你对时代与地域的判断正确，留下比盲目离开更可行；铺保文书一旦在华界办妥，外人街区的误导告示便不再能动摇你的落脚。',
      choices: [
        {
          id: 'c_stay_success',
          text: '接受担保，在城中立足',
          next: 'ending_success_stay',
          strategyTags: ['rely_on_relations', 'follow_institution'],
          settlementNote: '你接受担保，在正确规矩下站稳了脚跟。',
          condition: { type: 'hypothesisMatch', field: 'period', value: '民国初年' },
        },
        {
          id: 'c_stay_partial',
          text: '勉强留下',
          next: 'ending_partial_stay',
          strategyTags: ['rely_on_relations'],
          settlementNote: '你勉强留下，担保并不稳固。',
        },
      ],
    },
    {
      id: 'scene_leave',
      type: 'scene',
      title: '离城',
      background: 'early-republic-station',
      text: '你离开这座通商口岸，躲过了证件与铺保的压力，却必须在别处自行解决食宿。身后电车铃声渐远，两套告示都再也帮不上你。',
      choices: [
        {
          id: 'c_leave_end',
          text: '继续赶路',
          next: 'ending_partial_leave',
          strategyTags: ['avoid_transfer'],
          settlementNote: '你连夜离城，把证件危机甩在身后，却也失去立足。',
        },
      ],
    },
    {
      id: 'ending_success_stay',
      type: 'ending',
      title: '城中立足',
      outcome: 'success',
      score: 82,
      text: '你在城中获得短期担保，找到了继续生存的位置。新旧交替的街面上，理解铺保与分区规矩比口号更重要。',
      unlockSources: ['er_s1', 'er_s2'],
    },
    {
      id: 'ending_partial_stay',
      type: 'ending',
      title: '悬居城中',
      outcome: 'partial',
      score: 48,
      text: '你留在城里，却始终没有完全融入。你活了下来，但随时可能被新的查验打乱安排。',
      unlockSources: ['er_s3'],
    },
    {
      id: 'ending_partial_leave',
      type: 'ending',
      title: '夜离城区',
      outcome: 'partial',
      score: 48,
      text: '你离开了这座口岸城市，躲过了证件压力，却仍未找到真正安身之处。',
      unlockSources: ['er_s1'],
    },
    {
      id: 'ending_exposed',
      type: 'ending',
      title: '来历可疑',
      outcome: 'failure',
      score: 18,
      text: '你的说法与本地实际规则严重不符。被怀疑往往意味着失去担保与落脚处，你只能被逐出客栈。',
      unlockSources: ['er_s2'],
    },
    {
      id: 'ending_exhaustion',
      type: 'ending',
      title: '力竭',
      outcome: 'failure',
      score: 18,
      text: '你在电车和洋行之间耗尽最后一丝体力，再未能撑到下一个可容身之处。',
    },
    {
      id: 'ending_critical_injury',
      type: 'ending',
      title: '伤病',
      outcome: 'failure',
      score: 18,
      text: '伤病让你无法继续在这座口岸城市行动。近代街市不会为无法行动的人停留。',
    },
    {
      id: 'ending_exposed_stat',
      type: 'ending',
      title: '嫌疑',
      outcome: 'failure',
      score: 18,
      text: '关于你的议论已经扩散，客栈与商铺都不再欢迎你。',
    },
  ],
}
