import type { LevelPack } from '../../../game/types'

export const midTangLevel: LevelPack = {
  id: 'mid-tang',
  title: '长安客寄',
  theme: 'mid-tang',
  eraLabel: '盛唐',
  year: 742,
  regionLabel: '长安',
  oneLiner: '你在坊门外醒来，无本坊籍，必须在闭坊鼓前找到保人作保的寄住处。',
  coreCrisis: '无本坊户籍与保人——坊市制与宵禁下，无籍者不得随意过夜，闭坊后将被驱离。',
  historicalBackground:
    '公元742年，京师仍行坊市制。诸坊以鼓报时，日暮闭坊门，行人须有本坊籍或保人作保方可寄住。开元通宝流通广泛，市口胡商与驿使往来频繁，但繁华不等于夜间自由。外来者若无坊正认可的寄住登记，只能在闭坊前找到落脚点，否则将被坊门吏员驱离或扣留问话。',
  startNodeId: 'scene_awakening',
  correctAnswers: {
    period: '盛唐',
    region: '长安',
    identities: ['lodger', 'porter', 'messenger', 'servant'],
  },
  sources: [
    {
      id: 'mt_s1',
      title: '唐六典·尚书省',
      citation: '《唐六典》卷六 尚书省',
      factType: 'historical',
      summary: '唐代京师行坊市制，诸坊以鼓报时，闭坊门以禁夜行。',
      grade: 'A',
      author: '李林甫等',
      createdOrPublished: '738年',
      locator: '卷六 尚书省 左右金吾卫条',
      supports: '可证实唐代京师坊市制与鼓制宵禁并存，坊门吏员负责启闭与查验。',
      cannotProve: '无法证明742年某一坊门的具体查验力度，亦不能据本条推断个人能否寄住。',
    },
    {
      id: 'mt_s2',
      title: '唐代坊市制度与寄住管理研究',
      citation: '学界关于唐代坊正、保人与寄住登记的综合研究',
      factType: 'inference',
      summary: '外来者须由保人作保，经坊正登记后方可寄住本坊。',
      grade: 'B',
      author: '唐史学界',
      createdOrPublished: '20—21世纪',
      locator: '坊市寄住与保人制度相关章节',
      supports: '可推断无本坊籍者须保人作保方可寄住；坊正登记是常见程序。',
      cannotProve: '无法还原742年某一坊的实际执行细节，亦不能证明所有坊一律严查。',
    },
    {
      id: 'mt_s3',
      title: '开元通宝与长安物价',
      citation: '唐代开元通宝流通与京师物价记载',
      factType: 'historical',
      summary: '开元通宝是主要流通货币，市口物价因物而异。',
      grade: 'A',
      author: '唐代经济史研究者',
      createdOrPublished: '唐代（文献成书年代不一）',
      locator: '开元通宝流通与物价相关记载',
      supports: '可证实开元通宝为主要货币，市口交易活跃。',
      cannotProve: '无法给出742年某一市口的精确物价，亦不能据货币推断具体坊名。',
    },
  ],
  identities: [
    {
      id: 'lodger',
      label: '无籍的外来寄住者',
      description: '你没有本坊户籍，只能寻找保人作保或临时依附他人。',
      background: {
        livelihood: '无固定生计，靠帮工、帮佣或临时差事过日',
        socialPosition: '外来寄住者，不在本坊正式编户',
        affiliation: '无所依附，或临时混在市口人群中',
        rightsAndLimits: '无权在本坊自由过夜，须保人作保方可寄住',
        exposureReason: '无本坊籍与保人，无法应对坊门盘查',
      },
      sourceIds: ['mt_s2', 'mt_s1'],
      startingStats: { stamina: 55, wealth: 10, exposure: 25 },
      flags: ['no_fang_hukou'],
    },
    {
      id: 'porter',
      label: '随商队入城的脚夫',
      description: '你熟悉市口道路，却与商队失散，需重新找到可依附的队伍。',
      background: {
        livelihood: '以肩挑背扛、随队运输为业',
        socialPosition: '依附商队的底层劳力',
        affiliation: '与商队失散，暂无所属队伍',
        rightsAndLimits: '熟悉市口但不能独自寄住，需商队头目或保人作保',
        exposureReason: '独行脚夫身份可疑，缺少雇主信物或担保',
      },
      sourceIds: ['mt_s1', 'mt_s3'],
      startingStats: { stamina: 75, wealth: 12, exposure: 12 },
      flags: ['knows_market'],
    },
    {
      id: 'messenger',
      label: '持有过所的差遣人员',
      description: '你携有过所或封事，但并不知道是否仍被本坊承认。',
      background: {
        livelihood: '以递送公文、传递消息为业',
        socialPosition: '低阶差遣人员，非正式朝廷命官',
        affiliation: '依附官府或驿馆的临时任务',
        rightsAndLimits: '凭过所可有限通行，但需对答行文样式与去向',
        exposureReason: '过所若与吏员所识不符，或答不上细节，立刻暴露',
      },
      sourceIds: ['mt_s2', 'mt_s3'],
      startingStats: { stamina: 65, wealth: 18, exposure: 15 },
      flags: ['has_document'],
    },
    {
      id: 'servant',
      label: '依附主家入坊的仆从',
      description: '你原本随主家入坊，途中与主人失散，需重新找到可依附的主家。',
      background: {
        livelihood: '服侍主家，承担杂役与随侍',
        socialPosition: '人身依附的仆从，非自由编户',
        affiliation: '原随主家入坊，途中与主人失散',
        rightsAndLimits: '依附主家时可获庇护，但须对答主家名号与来历',
        exposureReason: '找不到主家，无法证明现有依附关系',
      },
      sourceIds: ['mt_s1', 'mt_s2'],
      startingStats: { stamina: 60, wealth: 15, exposure: 10 },
      flags: ['has_master_hint'],
    },
  ],
  evidence: [
    {
      id: 'mt_e1',
      title: '开元通宝与胡饼',
      description: '市口交易中仍使用开元通宝，胡饼价格因铺面而异。',
      category: '货币与交易',
      strength: 'strong',
      sourceId: 'mt_s3',
      hints: { period: '盛唐', region: '京师' },
    },
    {
      id: 'mt_e2',
      title: '坊门与鼓声',
      description: '坊门吏员以鼓报时，日暮闭坊，行人须在本坊寄住或离开。',
      category: '官制与法律',
      strength: 'strong',
      sourceId: 'mt_s1',
      hints: { period: '盛唐' },
    },
    {
      id: 'mt_e3',
      title: '保人作保',
      description: '坊正处要求外来者出示保人作保，无保人者不得寄住。',
      category: '社会习俗',
      strength: 'strong',
      sourceId: 'mt_s2',
      hints: { identity: '需保人作保' },
    },
    {
      id: 'mt_e4',
      title: '市口招牌',
      description: '市口铺面招牌字体规整，似为盛世京师风貌。',
      category: '文字与文书',
      strength: 'weak',
      sourceId: 'mt_s1',
      hints: { period: '盛唐' },
    },
    {
      id: 'mt_e5',
      title: '行人口述',
      description: '有人说"圣人万寿"，又有人说"胡商比往年更多"，信息互相补充。',
      category: '语言与称谓',
      strength: 'misleading',
      sourceId: 'mt_s2',
      hints: { period: '盛唐' },
    },
    {
      id: 'mt_e6',
      title: '宽街与里坊',
      description: '街道宽阔、坊墙高耸，表明此地为大城诸坊之一。',
      category: '交通与通信',
      strength: 'strong',
      sourceId: 'mt_s1',
      hints: { region: '大城诸坊' },
    },
  ],
  nodes: [
    {
      id: 'scene_awakening',
      type: 'scene',
      title: '坊外醒来',
      background: 'mid-tang-fang',
      text: '你在坊墙外的市口边醒来。远处鼓声隐约，行人以"使君""坊正"相称。你不知道自己为何在此，但腹中饥饿，且日头西斜——你必须尽快弄清能否在本坊过夜。',
      revealEvidence: ['mt_e2', 'mt_e6'],
      choices: [
        {
          id: 'c_follow_crowd',
          text: '随人流向坊门移动',
          next: 'scene_fang_gate',
          strategyTags: ['avoid_transfer'],
          settlementNote: '你选择随人流接近坊门，以最低暴露代价摸清规矩。',
          effects: [{ type: 'modifyStat', stat: 'stamina', delta: -8 }],
        },
        {
          id: 'c_check_body',
          text: '先检查随身物品与衣物',
          next: 'scene_inventory',
          strategyTags: ['conceal_identity'],
          settlementNote: '你暂缓前行，先确认身上是否还有可用凭证。',
        },
      ],
    },
    {
      id: 'scene_inventory',
      type: 'scene',
      title: '随身之物',
      background: 'mid-tang-fang',
      text: '你的衣料并不华丽，却也不像寻常农人。若你记得自己携带过所或主家信物，或许还能换取寄住；若没有，就必须依赖保人作保。',
      choices: [
        {
          id: 'c_has_doc',
          text: '检查是否有过所或信物',
          next: 'scene_fang_gate',
          condition: { type: 'flag', flag: 'has_document' },
          strategyTags: ['follow_institution'],
          settlementNote: '你确认过所仍在，文书线由此展开。',
          effects: [{ type: 'revealEvidence', evidenceId: 'mt_e3' }],
        },
        {
          id: 'c_no_doc',
          text: '确认没有可用凭证，只能先找地方落脚',
          next: 'scene_fang_gate',
          condition: { type: 'flag', flag: 'has_document', value: false },
          strategyTags: ['conceal_identity'],
          settlementNote: '你确认无凭证可用，只能以过路者身份试探。',
          effects: [
            { type: 'modifyStat', stat: 'exposure', delta: 5 },
            { type: 'revealEvidence', evidenceId: 'mt_e5' },
          ],
        },
      ],
    },
    {
      id: 'scene_fang_gate',
      type: 'scene',
      title: '坊门外',
      background: 'mid-tang-fang',
      text: '坊门外有人以开元通宝买胡饼，市口热闹。守门吏员问你是哪里的"客"，有无本坊籍或保人作保。你意识到，在这里，寄住资格比力气更重要。',
      revealEvidence: ['mt_e1', 'mt_e4'],
      choices: [
        {
          id: 'c_claim_traveler',
          text: '自称过路行人，请求借宿',
          next: 'scene_inn',
          strategyTags: ['conceal_identity'],
          settlementNote: '你以过路行人自称，换取进入市口的机会。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 8 }],
        },
        {
          id: 'c_show_document',
          text: '出示过所，称有公务在身',
          next: 'scene_inn',
          condition: { type: 'flag', flag: 'has_document' },
          strategyTags: ['follow_institution'],
          settlementNote: '你出示过所，以差遣人员身份降低怀疑。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: -5 }],
        },
        {
          id: 'c_find_master',
          text: '打听是否有人认得你的主家',
          next: 'scene_inn',
          condition: { type: 'flag', flag: 'has_master_hint' },
          strategyTags: ['rely_on_relations'],
          settlementNote: '你沿依附线打听主家下落，寻求庇护。',
        },
        {
          id: 'c_porter_offer',
          text: '主动帮商队搬运货物，换一顿食',
          next: 'scene_porter_labor',
          condition: { type: 'flag', flag: 'knows_market' },
          strategyTags: ['labor_trade'],
          settlementNote: '你以劳力换取信任，脚夫劳动线由此展开。',
        },
      ],
    },
    {
      id: 'scene_inn',
      type: 'scene',
      title: '市口邸店',
      background: 'mid-tang-inn',
      speaker: '店主',
      text: '店主一边擦案一边打量你："近来坊门查得紧，无保人作保者，最好莫乱说话。你若想在本坊过夜，得先弄清闭坊鼓几时敲响。"',
      revealEvidence: ['mt_e3'],
      choices: [
        {
          id: 'c_listen',
          text: '先听邸店中人议论坊市规矩',
          next: 'scene_rumors',
          strategyTags: ['rely_on_relations'],
          settlementNote: '你从邸店闲谈中获取坊市规矩碎片。',
          effects: [{ type: 'revealEvidence', evidenceId: 'mt_e5' }],
        },
        {
          id: 'c_buy_food',
          text: '用开元通宝买胡饼充饥',
          next: 'scene_rumors',
          strategyTags: ['exchange_resources'],
          settlementNote: '你花费通宝换得体力，继续收集线索。',
          effects: [
            { type: 'modifyStat', stat: 'wealth', delta: -5 },
            { type: 'modifyStat', stat: 'stamina', delta: 10 },
          ],
        },
      ],
    },
    {
      id: 'scene_rumors',
      type: 'scene',
      title: '传闻与线索',
      background: 'mid-tang-inn',
      text: '有人提及"圣人万寿"，也有人只说"坊正今日催寄住登记比往年更急"。这些说法都不足以单独定年，但足以说明：你所在的不是可随意夜行的岁月。你必须选择下一步的生存策略。',
      choices: [
        {
          id: 'c_submit_hypothesis',
          text: '整理线索，形成对年代与身份的判断',
          next: 'scene_decision',
          strategyTags: ['follow_institution'],
          settlementNote: '你整理已知线索，准备做出关键抉择。',
        },
        {
          id: 'c_lodger_hide',
          text: '趁闭坊前离开邸店，躲入市口后巷',
          next: 'scene_lodger_hide',
          condition: { type: 'flag', flag: 'no_fang_hukou' },
          strategyTags: ['conceal_identity', 'avoid_transfer'],
          settlementNote: '你选择躲避盘查，无籍躲避线由此展开。',
        },
        {
          id: 'c_messenger_route',
          text: '向脚夫打听坊正处，准备持过所登记',
          next: 'scene_curfew_info',
          condition: { type: 'flag', flag: 'has_document' },
          strategyTags: ['follow_institution'],
          settlementNote: '你沿文书线打听坊正，准备凭过所登记。',
        },
        {
          id: 'c_servant_master',
          text: '按主家名号打听，寻坊正引荐',
          next: 'scene_registration',
          condition: { type: 'flag', flag: 'has_master_hint' },
          strategyTags: ['rely_on_relations'],
          settlementNote: '你沿依附线寻找保人作保，直接求寄住。',
        },
        {
          id: 'c_ask_curfew_any',
          text: '向店主打听闭坊鼓几时敲响',
          next: 'scene_curfew_info',
        },
      ],
    },
    {
      id: 'scene_curfew_info',
      type: 'scene',
      title: '闭坊消息',
      background: 'mid-tang-curfew',
      text: '坊正处确在催寄住登记。无保人作保者会被劝离坊外，持有过所者则需对得上样式与去向。脚夫们低声说，今日闭坊鼓比往年敲得更早。',
      revealEvidence: ['mt_e3'],
      choices: [
        {
          id: 'c_to_decision',
          text: '带着这些消息回去整理判断',
          next: 'scene_decision',
          strategyTags: ['follow_institution'],
          settlementNote: '你掌握闭坊情报，回到抉择节点。',
        },
      ],
    },
    {
      id: 'scene_lodger_hide',
      type: 'scene',
      title: '后巷藏身',
      background: 'mid-tang-curfew',
      text: '你在市口后巷中缩着身子，远处传来闭坊鼓声。没有保人作保，你不敢走坊门正路；但躲藏也意味着闭坊后无处容身。你必须决定是继续躲，还是冒险混入下一波入坊人群。',
      choices: [
        {
          id: 'c_hide_flee',
          text: '趁鼓未敲满沿小巷离开，避开坊门',
          next: 'ending_partial_flee',
          strategyTags: ['avoid_transfer', 'conceal_identity'],
          settlementNote: '你沿小巷夜行，躲过当场查验但尚未立足。',
          effects: [
            { type: 'modifyStat', stat: 'stamina', delta: -18 },
            { type: 'modifyStat', stat: 'exposure', delta: -8 },
          ],
        },
        {
          id: 'c_hide_blend',
          text: '混入入坊人群，尝试重新进入市口',
          next: 'scene_decision',
          strategyTags: ['conceal_identity'],
          settlementNote: '你冒险混入人群，暴露风险上升。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 12 }],
        },
        {
          id: 'c_hide_caught',
          text: '后巷外有人举火查问，你应答失当',
          next: 'ending_exposed',
          condition: { type: 'hypothesisMismatch', field: 'period', value: '盛唐' },
          strategyTags: ['conceal_identity'],
          settlementNote: '你应答露出破绽，被当场扣留问话。',
        },
      ],
    },
    {
      id: 'scene_porter_labor',
      type: 'scene',
      title: '以力换食',
      background: 'mid-tang-fang',
      text: '你帮商队与市口长者搬运货物，换来一顿胡饼与半日歇脚。对方不问你太多来历，只看你肯不肯出力。脚夫在盛世里，有时比过所更管用——但出力换不来本坊籍，只能换一时信任。',
      choices: [
        {
          id: 'c_labor_register',
          text: '继续出力，请求保人作保寄住',
          next: 'ending_success_belong',
          strategyTags: ['labor_trade', 'rely_on_relations'],
          settlementNote: '你以劳动换取保人作保，暂获寄住。',
          effects: [
            { type: 'modifyStat', stat: 'stamina', delta: -10 },
            { type: 'modifyStat', stat: 'exposure', delta: -12 },
          ],
        },
        {
          id: 'c_labor_move_on',
          text: '歇脚后继续随商队入坊',
          next: 'scene_decision',
          strategyTags: ['labor_trade'],
          settlementNote: '你随商队继续前行，劳动线汇入抉择节点。',
          effects: [{ type: 'modifyStat', stat: 'stamina', delta: 5 }],
        },
      ],
    },
    {
      id: 'scene_decision',
      type: 'scene',
      title: '抉择',
      background: 'mid-tang-curfew',
      text: '闭坊鼓声渐近。你必须决定：是持过所登记寄住，还是留在市口寻找保人作保。若你对年代和身份判断有误，错误自称会立刻引来坊正怀疑。',
      choices: [
        {
          id: 'c_official_claim',
          text: '自称朝廷属吏，请求坊正庇护',
          next: 'scene_official_route',
          requiresCorrectHypothesis: 'period',
          strategyTags: ['follow_institution'],
          settlementNote: '你以官方身份自称，冒了暴露风险。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 15 }],
        },
        {
          id: 'c_local_hide',
          text: '留在市口，先找保人作保再寄住',
          next: 'scene_registration',
          strategyTags: ['rely_on_relations'],
          settlementNote: '你选择依附保人，寻求寄住登记。',
          effects: [{ type: 'modifyStat', stat: 'stamina', delta: -5 }],
        },
        {
          id: 'c_use_document',
          text: '持过所登记，按文书路线寄住',
          next: 'scene_document_route',
          condition: { type: 'flag', flag: 'has_document' },
          requiresCorrectHypothesis: 'identity',
          strategyTags: ['follow_institution'],
          settlementNote: '你持过所登记，文书线进入最后阶段。',
        },
      ],
    },
    {
      id: 'scene_official_route',
      type: 'scene',
      title: '冒称官吏',
      background: 'mid-tang-curfew',
      text: '你以不符时宜的自称应对坊正盘查，吏员越听越疑。若你其实不了解当时官制细节，这一步几乎等于自证可疑。',
      choices: [
        {
          id: 'c_exposed',
          text: '强行要求寄住',
          next: 'ending_exposed',
          condition: { type: 'hypothesisMismatch', field: 'period', value: '盛唐' },
          strategyTags: ['follow_institution'],
          settlementNote: '你强行要求寄住，因年代判断错误而暴露。',
        },
        {
          id: 'c_recover',
          text: '改口称过路行人，请求暂留',
          next: 'scene_registration',
          strategyTags: ['conceal_identity'],
          settlementNote: '你改口称过路行人，退回依附路线。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 10 }],
        },
      ],
    },
    {
      id: 'scene_document_route',
      type: 'scene',
      title: '持过所登记',
      background: 'mid-tang-curfew',
      text: '过所样式与坊正所识相符，你得以登记寄住。但若你并不真正理解文书所代表的职责，前方仍可能因答不上细节而暴露。',
      choices: [
        {
          id: 'c_success_doc',
          text: '按过所指示完成寄住登记',
          next: 'ending_success_document',
          condition: { type: 'hypothesisMatch', field: 'period', value: '盛唐' },
          strategyTags: ['follow_institution'],
          settlementNote: '你凭过所完成登记，文书线达成寄住。',
        },
        {
          id: 'c_fail_doc',
          text: '继续冒名登记',
          next: 'ending_exposed',
          condition: { type: 'hypothesisMismatch', field: 'period', value: '盛唐' },
          strategyTags: ['conceal_identity'],
          settlementNote: '你冒名登记，因判断失误而被识破。',
        },
      ],
    },
    {
      id: 'scene_registration',
      type: 'scene',
      title: '保人作保',
      background: 'mid-tang-inn',
      text: '你帮市口长者搬运货物，换取一晚歇脚。对方不问你太多，只问你是否愿意请保人作保、在坊正处登记为"寄住客"。这是盛世里最常见的过夜方式——依附线在此收束。',
      choices: [
        {
          id: 'c_register',
          text: '接受作保，暂时寄住此坊',
          next: 'ending_success_belong',
          strategyTags: ['rely_on_relations', 'follow_institution'],
          settlementNote: '你接受保人作保，依附线达成寄住。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: -15 }],
        },
        {
          id: 'c_refuse_register',
          text: '拒绝作保，闭坊前离开坊外',
          next: 'ending_partial_flee',
          strategyTags: ['avoid_transfer'],
          settlementNote: '你拒绝作保离开坊外，暂脱险但未立足。',
          effects: [
            { type: 'modifyStat', stat: 'stamina', delta: -20 },
            { type: 'modifyStat', stat: 'exposure', delta: 10 },
          ],
        },
      ],
    },
    {
      id: 'ending_success_belong',
      type: 'ending',
      title: '暂得寄住',
      outcome: 'success',
      text: '你在坊正处登记为寄住客，暂时获得了可被本坊承认的过夜资格。闭坊鼓敲响时，你已在邸店歇下。',
      unlockSources: ['mt_s1', 'mt_s2'],
    },
    {
      id: 'ending_success_document',
      type: 'ending',
      title: '过所登记',
      outcome: 'success',
      text: '你凭过所完成寄住登记，并在闭坊前找到了可歇脚的邸店。你仍不知明日几何，但至少没有被当场识破。',
      unlockSources: ['mt_s2', 'mt_s3'],
    },
    {
      id: 'ending_partial_flee',
      type: 'ending',
      title: '闭坊前离去',
      outcome: 'partial',
      text: '你在闭坊鼓敲响前离开坊外，躲过了当场查验，但饥饿与疲惫仍在累积。你活了下来，却仍未真正立足。',
      unlockSources: ['mt_s3'],
    },
    {
      id: 'ending_exposed',
      type: 'ending',
      title: '来历败露',
      outcome: 'failure',
      text: '你的说法与时代细节对不上，坊正将你扣下问话。在缺少保人作保的情况下，这通常意味着失去在本坊过夜的能力。',
      unlockSources: ['mt_s2'],
    },
    {
      id: 'ending_exhaustion',
      type: 'ending',
      title: '力竭倒毙',
      outcome: 'failure',
      text: '你在市口倒下，再未醒来。体力与粮食和寄住资格一样，都是生存必需品。',
    },
    {
      id: 'ending_critical_injury',
      type: 'ending',
      title: '伤重不治',
      outcome: 'failure',
      text: '伤病耗尽了你最后一点行动能力。你未能走到下一个可以寄住的地方。',
    },
    {
      id: 'ending_exposed_stat',
      type: 'ending',
      title: '嫌疑缠身',
      outcome: 'failure',
      text: '周围人对你的怀疑已到无法掩饰的地步。你已无法再以任何身份自如行动。',
    },
  ],
}
