import type { LevelPack } from '../../../game/types'

export const northernSongLevel: LevelPack = {
  id: 'northern-song',
  title: '汴京客途',
  theme: 'northern-song',
  eraLabel: '北宋',
  year: 1085,
  regionLabel: '汴京',
  startNodeId: 'scene_city_gate',
  correctAnswers: {
    period: '北宋',
    region: '汴京',
    identities: ['servant', 'merchant_apprentice', 'traveler', 'craftsman'],
  },
  sources: [
    {
      id: 'ns_s1',
      title: '东京梦华录',
      citation: '孟元老《东京梦华录》',
      factType: 'historical',
      summary: '北宋汴京城市商业繁荣，行市、邸店与行业规则并存。',
    },
    {
      id: 'ns_s2',
      title: '宋会要辑稿·食货',
      citation: '《宋会要辑稿》食货相关条目',
      factType: 'historical',
      summary: '北宋铜钱、交子并用，城市物价与行业管理有明确制度。',
    },
    {
      id: 'ns_s3',
      title: '宋代城市行会研究',
      citation: '学界关于宋代行会、担保与雇役的综合研究',
      factType: 'inference',
      summary: '外来者入城谋生需行业担保或熟人引见。',
    },
  ],
  identities: [
    {
      id: 'servant',
      label: '随主入城的仆役',
      description: '你从外地随主人入汴，却在人群失散，需找到旧主或新雇主。',
      startingStats: { stamina: 60, wealth: 10, exposure: 18 },
      flags: ['has_master_token'],
    },
    {
      id: 'merchant_apprentice',
      label: '商铺学徒',
      description: '你识得一些行市规矩，但缺少独立担保。',
      startingStats: { stamina: 65, wealth: 22, exposure: 12 },
      flags: ['knows_trade'],
    },
    {
      id: 'traveler',
      label: '初到汴京的外地客人',
      description: '你带有路引和少量铜钱，却不熟悉汴京行业规则。',
      startingStats: { stamina: 70, wealth: 25, exposure: 20 },
      flags: ['has_travel_permit'],
    },
    {
      id: 'craftsman',
      label: '寻活的工匠',
      description: '你凭手艺谋生，但需先找到行会认可才能稳定接活。',
      startingStats: { stamina: 68, wealth: 16, exposure: 14 },
      flags: ['has_skill'],
    },
  ],
  evidence: [
    {
      id: 'ns_e1',
      title: '交子与铜钱',
      description: '市肆中既见铜钱，又见交子，说明商业高度发达。',
      category: '货币与交易',
      strength: 'strong',
      sourceId: 'ns_s2',
      hints: { period: '北宋' },
    },
    {
      id: 'ns_e2',
      title: '州桥夜市',
      description: '夜市直至三更，酒楼、邸店、行市鳞次栉比，符合汴京特征。',
      category: '城市与建筑',
      strength: 'strong',
      sourceId: 'ns_s1',
      hints: { region: '汴京' },
    },
    {
      id: 'ns_e3',
      title: '行会引见',
      description: '外来工匠和学徒需由行老或店主担保，方可长期留城。',
      category: '社会习俗',
      strength: 'strong',
      sourceId: 'ns_s3',
      hints: { identity: '需担保' },
    },
    {
      id: 'ns_e4',
      title: '年号纪年',
      description: '文书使用“元丰”年号，表明时间在神宗朝。',
      category: '文字与文书',
      strength: 'strong',
      sourceId: 'ns_s2',
      hints: { period: '北宋元丰年间' },
    },
    {
      id: 'ns_e5',
      title: '辽使传闻',
      description: '酒肆中有人谈论“北界使节”，容易误以为是更晚的宋辽关系。',
      category: '语言与称谓',
      strength: 'misleading',
      sourceId: 'ns_s1',
      hints: { period: '北宋' },
    },
    {
      id: 'ns_e6',
      title: '汴河漕运',
      description: '漕船沿汴河入城，说明此城为水运枢纽。',
      category: '交通与通信',
      strength: 'weak',
      sourceId: 'ns_s1',
      hints: { region: '汴京' },
    },
  ],
  nodes: [
    {
      id: 'scene_city_gate',
      type: 'scene',
      title: '入城',
      background: 'northern-song-gate',
      text: '你在城门外被问起来意。城内外人声鼎沸，漕船沿汴河入城，市肆招牌与行市名称显示这是一座高度商业化的城市。你不记得自己为何在此，但必须先入城。',
      revealEvidence: ['ns_e2', 'ns_e6'],
      choices: [
        {
          id: 'c_enter_with_permit',
          text: '出示路引，称来汴探亲',
          next: 'scene_market',
          condition: { type: 'flag', flag: 'has_travel_permit' },
        },
        {
          id: 'c_enter_with_token',
          text: '出示主人信物，称随主入城',
          next: 'scene_market',
          condition: { type: 'flag', flag: 'has_master_token' },
        },
        {
          id: 'c_enter_work',
          text: '称来寻行业活计',
          next: 'scene_market',
          condition: { type: 'flag', flag: 'has_skill' },
        },
        {
          id: 'c_enter_generic',
          text: '称来投亲靠友，先找地方落脚',
          next: 'scene_market',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 6 }],
        },
      ],
    },
    {
      id: 'scene_market',
      type: 'scene',
      title: '行市之中',
      background: 'northern-song-market',
      text: '你在行市中看到交子与铜钱并用，文书上写着“元丰”年号。繁华不等于自由——每个行业都有自己的规矩与担保。',
      revealEvidence: ['ns_e1', 'ns_e4'],
      choices: [
        {
          id: 'c_find_inn',
          text: '先找邸店住下，再打听消息',
          next: 'scene_inn',
          effects: [
            { type: 'modifyStat', stat: 'wealth', delta: -8 },
            { type: 'modifyStat', stat: 'stamina', delta: 8 },
          ],
        },
        {
          id: 'c_find_guild',
          text: '直接去行会口打听担保',
          next: 'scene_guild',
          condition: { type: 'flag', flag: 'knows_trade' },
        },
        {
          id: 'c_ask_around',
          text: '在市肆中打听消息',
          next: 'scene_inn',
          effects: [{ type: 'revealEvidence', evidenceId: 'ns_e5' }],
        },
      ],
    },
    {
      id: 'scene_inn',
      type: 'scene',
      title: '邸店',
      background: 'northern-song-inn',
      speaker: '店主',
      text: '店主打量你的衣着：“客官若是短住，钱够就行；若要留城谋生，得找行老作保。近来查得紧，外来无保人者，夜里也不安稳。”',
      revealEvidence: ['ns_e3'],
      choices: [
        {
          id: 'c_rest',
          text: '先住下，整理已有线索',
          next: 'scene_hypothesis',
        },
        {
          id: 'c_seek_master',
          text: '按信物上所写地址寻找旧主',
          next: 'scene_master',
          condition: { type: 'flag', flag: 'has_master_token' },
        },
      ],
    },
    {
      id: 'scene_guild',
      type: 'scene',
      title: '行会口',
      background: 'northern-song-market',
      text: '行老问你师承何处、可曾做过何种活计。你能答上来，便有机会获得短期担保；答不上来，只能做零工。',
      choices: [
        {
          id: 'c_guild_accept',
          text: '以手艺换担保',
          next: 'scene_hypothesis',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: -8 }],
        },
        {
          id: 'c_guild_reject',
          text: '放弃担保，回邸店另作打算',
          next: 'scene_inn',
        },
      ],
    },
    {
      id: 'scene_master',
      type: 'scene',
      title: '寻主',
      background: 'northern-song-street',
      text: '你按信物找到一处宅门，门房却称主人数日前已离汴。你仍可使用信物证明“曾随主入城”，但需尽快找到新依附。',
      choices: [
        {
          id: 'c_master_done',
          text: '带着这一信息回去整理判断',
          next: 'scene_hypothesis',
        },
      ],
    },
    {
      id: 'scene_hypothesis',
      type: 'scene',
      title: '整理判断',
      background: 'northern-song-inn',
      text: '交子、元丰年号、汴河漕运与行市规矩，都指向一座特定的城市与时代。若你把这里当成任意“古代繁华都市”，接下来每一步都会付出代价。',
      choices: [
        {
          id: 'c_to_plan',
          text: '决定下一步生存策略',
          next: 'scene_plan',
        },
      ],
    },
    {
      id: 'scene_plan',
      type: 'scene',
      title: '谋生抉择',
      background: 'northern-song-market',
      text: '你可以尝试留在汴京靠担保谋生，也可以趁夜离开以避免暴露。若你误判时代，贸然使用不合时宜的称谓或制度知识，会立刻引起怀疑。',
      choices: [
        {
          id: 'c_stay_guild',
          text: '留城，凭行业规矩求保',
          next: 'scene_stay_route',
        },
        {
          id: 'c_claim_official',
          text: '自称京官亲属，要求特殊待遇',
          next: 'scene_wrong_claim',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 12 }],
        },
        {
          id: 'c_leave_city',
          text: '趁夜离城，另寻生路',
          next: 'scene_leave_route',
          effects: [{ type: 'modifyStat', stat: 'stamina', delta: -15 }],
        },
      ],
    },
    {
      id: 'scene_wrong_claim',
      type: 'scene',
      title: '不当自称',
      background: 'northern-song-street',
      text: '你的说法带有明显的时代错位——汴京市民或许听不懂你口中的“朝廷制度”，却听得懂你语气中的不当自信。',
      choices: [
        {
          id: 'c_wrong_fail',
          text: '坚持原说法',
          next: 'ending_exposed',
          condition: { type: 'hypothesisMismatch', field: 'period', value: '北宋' },
        },
        {
          id: 'c_wrong_recover',
          text: '改口称外地客人',
          next: 'scene_stay_route',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 8 }],
        },
      ],
    },
    {
      id: 'scene_stay_route',
      type: 'scene',
      title: '留城',
      background: 'northern-song-market',
      text: '你在行市做零工，渐渐有人愿意为你作保。若你对汴京与北宋的判断正确，留下比盲目离开更稳妥。',
      choices: [
        {
          id: 'c_stay_success',
          text: '接受担保，在汴京立足',
          next: 'ending_success_stay',
          condition: { type: 'hypothesisMatch', field: 'region', value: '汴京' },
        },
        {
          id: 'c_stay_partial',
          text: '勉强留下，但始终提心吊胆',
          next: 'ending_partial_stay',
        },
      ],
    },
    {
      id: 'scene_leave_route',
      type: 'scene',
      title: '离城',
      background: 'northern-song-gate',
      text: '你趁夜出城，躲过了行市担保的压力，却必须在城外自行解决食宿。',
      choices: [
        {
          id: 'c_leave_end',
          text: '继续赶路',
          next: 'ending_partial_leave',
        },
      ],
    },
    {
      id: 'ending_success_stay',
      type: 'ending',
      title: '汴京立足',
      outcome: 'success',
      text: '你在汴京获得担保，找到了可继续谋生的位置。繁华之城从不是无主之地，但你终于在其中站住了脚。',
      unlockSources: ['ns_s1', 'ns_s3'],
    },
    {
      id: 'ending_partial_stay',
      type: 'ending',
      title: '悬居城中',
      outcome: 'partial',
      text: '你留在汴京，却始终没有完全融入。你活了下来，但随时可能被新的查验打乱安排。',
      unlockSources: ['ns_s2'],
    },
    {
      id: 'ending_partial_leave',
      type: 'ending',
      title: '夜出汴京',
      outcome: 'partial',
      text: '你离开了汴京，躲过了城里的担保压力，却仍未找到真正安身之处。',
      unlockSources: ['ns_s1'],
    },
    {
      id: 'ending_exposed',
      type: 'ending',
      title: '行市起疑',
      outcome: 'failure',
      text: '你的说法与汴京日常规矩格格不入，行市中人开始对你避而远之。在这座讲究担保的城市里，被怀疑往往意味着失去一切。',
      unlockSources: ['ns_s3'],
    },
    {
      id: 'ending_exhaustion',
      type: 'ending',
      title: '力竭',
      outcome: 'failure',
      text: '你在拥挤的行市与邸店之间耗尽最后一丝体力，再未能撑到下一个可容身之处。',
    },
    {
      id: 'ending_critical_injury',
      type: 'ending',
      title: '伤病',
      outcome: 'failure',
      text: '伤病让你在汴京无法继续行动。繁华之城不会为无法行动的人停留。',
    },
    {
      id: 'ending_exposed_stat',
      type: 'ending',
      title: '嫌疑',
      outcome: 'failure',
      text: '关于你的议论已经扩散，行市与邸店都不再欢迎你。',
    },
  ],
}
