import type { LevelPack } from '../../../game/types'

export const earlyMingLevel: LevelPack = {
  id: 'early-ming',
  title: '应天路引',
  theme: 'early-ming',
  eraLabel: '明初',
  year: 1393,
  regionLabel: '应天府',
  oneLiner: '你在官道边醒来，无路引，必须在里甲盘查与关津验看之间找到活路。',
  coreCrisis: '无路引——明初里甲与关津制度要求行人持有路引方可远行，无引者随时可能被扣留问话。',
  historicalBackground:
    '公元1393年，明初里甲制度已全面推行。行人远行须持有路引，关津吏员与里甲盘查趋严。洪武通宝仍流通，但粮价因征役与催报波动。失去路引者只能依附商队、凭里长作保，或绕道小径躲避查验。这一关卡的危机，正是无路引者在严法中求存的真实困境。',
  startNodeId: 'scene_awakening',
  correctAnswers: {
    period: '明初',
    region: '应天府',
    identities: ['traveler', 'messenger', 'porter', 'tenant'],
  },
  sources: [
    {
      id: 'em_s1',
      title: '大明律·户律',
      citation: '《大明律》户律 户役门',
      factType: 'historical',
      summary: '明初规定行人远行须持有路引，关津验看方可通行。',
      grade: 'A',
      author: '刘惟谦等',
      createdOrPublished: '1397年（洪武三十年定本）',
      locator: '户律 户役门 路引条',
      supports: '可证实明初路引制度与关津验看并存，里甲催报与户籍控制相关。',
      cannotProve: '无法证明1393年某一关津的具体查验力度，亦不能据本条推断个人能否通行。',
    },
    {
      id: 'em_s2',
      title: '明代里甲制度与迁徙控制研究',
      citation: '学界关于明代里甲、路引与迁徙控制的综合研究',
      factType: 'inference',
      summary: '流民与过路者需依赖里长作保或官方路引方可通行。',
      grade: 'B',
      author: '明史学界',
      createdOrPublished: '20—21世纪',
      locator: '里甲与路引制度相关章节',
      supports: '可推断无路引者通行受限，需依附关系或里长作保；关津验视符合制度逻辑。',
      cannotProve: '无法还原1393年某一关津的实际执行细节，亦不能证明所有聚落一律严查。',
    },
    {
      id: 'em_s3',
      title: '洪武通宝与江南物价',
      citation: '明代洪武通宝流通与江南物价记载',
      factType: 'historical',
      summary: '洪武通宝是主要流通货币，粮价因征役波动。',
      grade: 'A',
      author: '明代经济史研究者',
      createdOrPublished: '明代（文献成书年代不一）',
      locator: '洪武通宝流通与粮价相关记载',
      supports: '可证实洪武通宝为主要货币，征役之年粮价高于承平之年。',
      cannotProve: '无法给出1393年某一聚落的精确粮价，亦不能据货币推断具体府境。',
    },
  ],
  identities: [
    {
      id: 'traveler',
      label: '丢失路引的过路者',
      description: '你失去了有效的路引，只能依附他人或躲避查验。',
      background: {
        livelihood: '无固定生计，靠帮工、帮佣或临时差事过日',
        socialPosition: '编户之外的过路者，路引遗失或过期',
        affiliation: '无所依附，或临时混在过路人群中',
        rightsAndLimits: '无权自由通行，不得请领官粮，易被扣留问话',
        exposureReason: '缺失路引，无法应对关津盘查',
      },
      sourceIds: ['em_s2', 'em_s1'],
      startingStats: { stamina: 55, wealth: 8, exposure: 25 },
      flags: ['no_luyin'],
    },
    {
      id: 'messenger',
      label: '传递公文的差遣人员',
      description: '你携有封套，但并不知道其中内容是否仍被承认。',
      background: {
        livelihood: '以递送封套、传递消息为业',
        socialPosition: '低阶差遣人员，非正式朝廷命官',
        affiliation: '依附雇主或地方官府的临时任务',
        rightsAndLimits: '凭封套可有限通行，但需对答行文样式与去向',
        exposureReason: '封套若与吏员所识不符，或答不上细节，立刻暴露',
      },
      sourceIds: ['em_s2', 'em_s3'],
      startingStats: { stamina: 65, wealth: 15, exposure: 15 },
      flags: ['has_document'],
    },
    {
      id: 'porter',
      label: '随队赶路的脚夫',
      description: '你熟悉道路，却与雇主失散，需重新找到可依附的队伍。',
      background: {
        livelihood: '以肩挑背扛、随队运输为业',
        socialPosition: '依附商队或里甲的底层劳力',
        affiliation: '与雇主失散，暂无所属队伍',
        rightsAndLimits: '熟悉道路但不能独自过关，需雇主或里长作保',
        exposureReason: '独行脚夫身份可疑，缺少雇主信物或担保',
      },
      sourceIds: ['em_s1', 'em_s3'],
      startingStats: { stamina: 75, wealth: 12, exposure: 12 },
      flags: ['knows_road'],
    },
    {
      id: 'tenant',
      label: '依附里甲的佃户',
      description: '你原本属于某处田庄，征役迫使你在外寻找旧主或新依附。',
      background: {
        livelihood: '耕作田庄，替里甲承役纳赋',
        socialPosition: '人身依附的下级佃户，非自由编户',
        affiliation: '原属某处田庄，途中与旧主失散',
        rightsAndLimits: '依附主家时可获庇护，但须承担役使与随调',
        exposureReason: '找不到旧主，无法证明现有依附关系',
      },
      sourceIds: ['em_s1', 'em_s2'],
      startingStats: { stamina: 60, wealth: 18, exposure: 10 },
      flags: ['has_patron_hint'],
    },
  ],
  evidence: [
    {
      id: 'em_e1',
      title: '洪武通宝与粮价',
      description: '道旁交易中仍使用洪武通宝，但一石粮价高于太平时期。',
      category: '货币与交易',
      strength: 'strong',
      sourceId: 'em_s3',
      hints: { period: '明初', region: '江南' },
    },
    {
      id: 'em_e2',
      title: '里甲与里长称谓',
      description: '地方吏员仍称"里长""甲首"，说明里甲制度仍在执行。',
      category: '官制与法律',
      strength: 'strong',
      sourceId: 'em_s1',
      hints: { period: '明初' },
    },
    {
      id: 'em_e3',
      title: '关津验看',
      description: '关津处要求出示路引或验视封套，无路引者不得随意通行。',
      category: '社会习俗',
      strength: 'strong',
      sourceId: 'em_s2',
      hints: { identity: '需路引或作保' },
    },
    {
      id: 'em_e4',
      title: '道旁里程碑',
      description: '官道旁里程碑年号模糊，但"洪"字可辨，似为明初年号系统。',
      category: '文字与文书',
      strength: 'weak',
      sourceId: 'em_s1',
      hints: { period: '明初' },
    },
    {
      id: 'em_e5',
      title: '过路者口述',
      description: '有人说"里甲催报比往年更急"，又有人说"新朝法严"，信息互相补充。',
      category: '语言与称谓',
      strength: 'misleading',
      sourceId: 'em_s2',
      hints: { period: '明初' },
    },
    {
      id: 'em_e6',
      title: '官道里程木',
      description: '官道旁里程标记指向府城方向，表明此地为府境要道。',
      category: '交通与通信',
      strength: 'strong',
      sourceId: 'em_s1',
      hints: { region: '府境要道' },
    },
  ],
  nodes: [
    {
      id: 'scene_awakening',
      type: 'scene',
      title: '道旁醒来',
      background: 'early-ming-road',
      text: '你在尘土飞扬的官道边醒来。道旁有人以"里长""甲首"相称，远处里程木指向府城方向。你不知道自己为何在此，但腹中饥饿，必须尽快找到可容身之处。',
      revealEvidence: ['em_e2', 'em_e6'],
      choices: [
        {
          id: 'c_follow_traffic',
          text: '随人流向最近的聚落移动',
          next: 'scene_village_gate',
          strategyTags: ['avoid_transfer'],
          settlementNote: '你选择随人流移动，以最低暴露代价接近聚落。',
          effects: [{ type: 'modifyStat', stat: 'stamina', delta: -8 }],
        },
        {
          id: 'c_check_body',
          text: '先检查随身物品与衣物',
          next: 'scene_inventory',
          strategyTags: ['conceal_identity'],
          settlementNote: '你暂缓前行，先确认身上是否还有可用凭证。',
        },
      ],
    },
    {
      id: 'scene_inventory',
      type: 'scene',
      title: '随身之物',
      background: 'early-ming-road',
      text: '你的衣料并不华丽，却也不像寻常农人。若你记得自己携带路引或雇主信物，或许还能换取通行；若没有，就必须依赖里长作保。',
      choices: [
        {
          id: 'c_has_doc',
          text: '检查是否有封套或信物',
          next: 'scene_village_gate',
          condition: { type: 'flag', flag: 'has_document' },
          strategyTags: ['follow_institution'],
          settlementNote: '你确认封套仍在，文书线由此展开。',
          effects: [{ type: 'revealEvidence', evidenceId: 'em_e3' }],
        },
        {
          id: 'c_no_doc',
          text: '确认没有可用凭证，只能先找地方落脚',
          next: 'scene_village_gate',
          condition: { type: 'flag', flag: 'has_document', value: false },
          strategyTags: ['conceal_identity'],
          settlementNote: '你确认无凭证可用，只能以过路者身份试探。',
          effects: [
            { type: 'modifyStat', stat: 'exposure', delta: 5 },
            { type: 'revealEvidence', evidenceId: 'em_e5' },
          ],
        },
      ],
    },
    {
      id: 'scene_village_gate',
      type: 'scene',
      title: '聚落外',
      background: 'early-ming-village',
      text: '聚落外有人以洪武通宝换粮，价格贵得惊人。守门者问你是哪里的"客"，有无路引。你意识到，在这里，来历比力气更重要。',
      revealEvidence: ['em_e1', 'em_e4'],
      choices: [
        {
          id: 'c_claim_traveler',
          text: '自称过路行人，请求借宿',
          next: 'scene_inn',
          strategyTags: ['conceal_identity'],
          settlementNote: '你以过路行人自称，换取进入聚落的机会。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 8 }],
        },
        {
          id: 'c_show_document',
          text: '出示封套，称有公务在身',
          next: 'scene_inn',
          condition: { type: 'flag', flag: 'has_document' },
          strategyTags: ['follow_institution'],
          settlementNote: '你出示封套，以公务行人身份降低怀疑。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: -5 }],
        },
        {
          id: 'c_find_patron',
          text: '打听是否有人认得你的旧主',
          next: 'scene_inn',
          condition: { type: 'flag', flag: 'has_patron_hint' },
          strategyTags: ['rely_on_relations'],
          settlementNote: '你沿依附线打听旧主下落，寻求里甲庇护。',
        },
        {
          id: 'c_porter_offer',
          text: '主动帮商队搬运粮袋，换一顿食',
          next: 'scene_porter_labor',
          condition: { type: 'flag', flag: 'knows_road' },
          strategyTags: ['labor_trade'],
          settlementNote: '你以劳力换取信任，脚夫劳动线由此展开。',
        },
      ],
    },
    {
      id: 'scene_inn',
      type: 'scene',
      title: '道旁客店',
      background: 'early-ming-village',
      speaker: '店主',
      text: '店主一边擦案一边打量你："近来道上查得紧，无路引者，最好莫乱说话。你若想往东，得先弄清是谁在盘查。"',
      revealEvidence: ['em_e3'],
      choices: [
        {
          id: 'c_listen',
          text: '先听客店中人议论局势',
          next: 'scene_rumors',
          strategyTags: ['rely_on_relations'],
          settlementNote: '你从客店闲谈中获取局势碎片。',
          effects: [{ type: 'revealEvidence', evidenceId: 'em_e5' }],
        },
        {
          id: 'c_buy_food',
          text: '用洪武通宝买饼充饥',
          next: 'scene_rumors',
          strategyTags: ['exchange_resources'],
          settlementNote: '你花费通宝换得体力，继续收集线索。',
          effects: [
            { type: 'modifyStat', stat: 'wealth', delta: -5 },
            { type: 'modifyStat', stat: 'stamina', delta: 10 },
          ],
        },
      ],
    },
    {
      id: 'scene_rumors',
      type: 'scene',
      title: '传闻与线索',
      background: 'early-ming-village',
      text: '有人提及"里甲催报"，也有人只说"新朝法严"。这些说法都不足以单独定年，但足以说明：你所在的不是可随意行走的岁月。你必须选择下一步的生存策略。',
      choices: [
        {
          id: 'c_submit_hypothesis',
          text: '整理线索，形成对年代与身份的判断',
          next: 'scene_decision',
          strategyTags: ['follow_institution'],
          settlementNote: '你整理已知线索，准备做出关键抉择。',
        },
        {
          id: 'c_traveler_hide',
          text: '趁夜离开客店，躲入道旁废弃仓窖',
          next: 'scene_traveler_hide',
          condition: { type: 'flag', flag: 'no_luyin' },
          strategyTags: ['conceal_identity', 'avoid_transfer'],
          settlementNote: '你选择躲避盘查，无引躲避线由此展开。',
        },
        {
          id: 'c_messenger_checkpoint',
          text: '向脚夫打听前方关津，准备持封套过关',
          next: 'scene_checkpoint',
          condition: { type: 'flag', flag: 'has_document' },
          strategyTags: ['follow_institution'],
          settlementNote: '你沿文书线打听关津，准备凭封套通行。',
        },
        {
          id: 'c_tenant_patron',
          text: '按旧主名号打听，寻里长引荐',
          next: 'scene_local_route',
          condition: { type: 'flag', flag: 'has_patron_hint' },
          strategyTags: ['rely_on_relations'],
          settlementNote: '你沿依附线寻找里长作保，直接求容身。',
        },
        {
          id: 'c_ask_checkpoint_any',
          text: '向店主打听前方关津情况',
          next: 'scene_checkpoint',
        },
      ],
    },
    {
      id: 'scene_checkpoint',
      type: 'scene',
      title: '关津消息',
      background: 'early-ming-checkpoint',
      text: '前方确有关津吏员验看行人。无路引者会被扣留问话，携带封套者则需对得上封套样式与去向。脚夫们低声说，最近查得比往年更紧。',
      revealEvidence: ['em_e3'],
      choices: [
        {
          id: 'c_to_decision',
          text: '带着这些消息回去整理判断',
          next: 'scene_decision',
          strategyTags: ['follow_institution'],
          settlementNote: '你掌握关津情报，回到抉择节点。',
        },
      ],
    },
    {
      id: 'scene_traveler_hide',
      type: 'scene',
      title: '仓窖藏身',
      background: 'early-ming-village',
      text: '你在废弃仓窖中缩着身子，远处传来更鼓与犬吠。没有路引，你不敢走大路；但躲藏也意味着饥饿一日日加重。你必须决定是继续躲，还是冒险混入下一波过路人群。',
      choices: [
        {
          id: 'c_hide_flee',
          text: '趁夜沿田间小径离开，避开关津',
          next: 'ending_partial_flee',
          strategyTags: ['avoid_transfer', 'conceal_identity'],
          settlementNote: '你沿小径夜行，躲过当场查验但尚未立足。',
          effects: [
            { type: 'modifyStat', stat: 'stamina', delta: -18 },
            { type: 'modifyStat', stat: 'exposure', delta: -8 },
          ],
        },
        {
          id: 'c_hide_blend',
          text: '混入过路人群，尝试重新进入聚落',
          next: 'scene_decision',
          strategyTags: ['conceal_identity'],
          settlementNote: '你冒险混入人群，暴露风险上升。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 12 }],
        },
        {
          id: 'c_hide_caught',
          text: '仓窖外有人举火查问，你应答失当',
          next: 'ending_exposed',
          condition: { type: 'hypothesisMismatch', field: 'period', value: '明初' },
          strategyTags: ['conceal_identity'],
          settlementNote: '你应答露出破绽，被当场扣留问话。',
        },
      ],
    },
    {
      id: 'scene_porter_labor',
      type: 'scene',
      title: '以力换食',
      background: 'early-ming-village',
      text: '你帮商队与里中长者搬运粮袋，换来一顿食与半日歇脚。对方不问你太多来历，只看你肯不肯出力。脚夫在严法里，有时比路引更管用——但出力换不来路引，只能换一时信任。',
      choices: [
        {
          id: 'c_labor_register',
          text: '继续出力，请求里长作保登记为"客"',
          next: 'ending_success_belong',
          strategyTags: ['labor_trade', 'rely_on_relations'],
          settlementNote: '你以劳动换取里中登记，暂获容身。',
          effects: [
            { type: 'modifyStat', stat: 'stamina', delta: -10 },
            { type: 'modifyStat', stat: 'exposure', delta: -12 },
          ],
        },
        {
          id: 'c_labor_move_on',
          text: '歇脚后继续随商队东行',
          next: 'scene_decision',
          strategyTags: ['labor_trade'],
          settlementNote: '你随商队继续前行，劳动线汇入抉择节点。',
          effects: [{ type: 'modifyStat', stat: 'stamina', delta: 5 }],
        },
      ],
    },
    {
      id: 'scene_decision',
      type: 'scene',
      title: '抉择',
      background: 'early-ming-road',
      text: '你必须决定：是继续向东依附大城，还是留在地方寻找可容身的里甲关系。若你对年代和身份判断有误，错误自称会立刻引来怀疑。',
      choices: [
        {
          id: 'c_east_official',
          text: '自称朝廷属吏，请求官方保护',
          next: 'scene_east_route',
          requiresCorrectHypothesis: 'period',
          strategyTags: ['follow_institution'],
          settlementNote: '你以官方身份自称，冒了暴露风险。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 15 }],
        },
        {
          id: 'c_local_hide',
          text: '留在地方，先找里长作保再行动',
          next: 'scene_local_route',
          strategyTags: ['rely_on_relations'],
          settlementNote: '你选择依附里甲，寻求里长作保。',
          effects: [{ type: 'modifyStat', stat: 'stamina', delta: -5 }],
        },
        {
          id: 'c_use_document',
          text: '持封套过卡，按文书路线前进',
          next: 'scene_document_route',
          condition: { type: 'flag', flag: 'has_document' },
          requiresCorrectHypothesis: 'identity',
          strategyTags: ['follow_institution'],
          settlementNote: '你持封套过关，文书线进入最后阶段。',
        },
      ],
    },
    {
      id: 'scene_east_route',
      type: 'scene',
      title: '东行',
      background: 'early-ming-checkpoint',
      text: '你以不符时宜的自称应对盘查，吏员越听越疑。若你其实不了解当时官制细节，这一步几乎等于自证可疑。',
      choices: [
        {
          id: 'c_exposed',
          text: '强行继续东行',
          next: 'ending_exposed',
          condition: { type: 'hypothesisMismatch', field: 'period', value: '明初' },
          strategyTags: ['follow_institution'],
          settlementNote: '你强行东行，因年代判断错误而暴露。',
        },
        {
          id: 'c_recover',
          text: '改口称过路行人，请求暂留',
          next: 'scene_local_route',
          strategyTags: ['conceal_identity'],
          settlementNote: '你改口称过路行人，退回依附路线。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 10 }],
        },
      ],
    },
    {
      id: 'scene_document_route',
      type: 'scene',
      title: '持封套前行',
      background: 'early-ming-checkpoint',
      text: '封套样式与吏员所识相符，你得以通过关津。但若你并不真正理解文书所代表的职责，前方仍可能因答不上细节而暴露。',
      choices: [
        {
          id: 'c_success_doc',
          text: '按封套指示前往下一处',
          next: 'ending_success_document',
          condition: { type: 'hypothesisMatch', field: 'period', value: '明初' },
          strategyTags: ['follow_institution'],
          settlementNote: '你凭封套通过盘查，文书线达成通行。',
        },
        {
          id: 'c_fail_doc',
          text: '继续冒名前行',
          next: 'ending_exposed',
          condition: { type: 'hypothesisMismatch', field: 'period', value: '明初' },
          strategyTags: ['conceal_identity'],
          settlementNote: '你冒名前行，因判断失误而被识破。',
        },
      ],
    },
    {
      id: 'scene_local_route',
      type: 'scene',
      title: '里甲依附',
      background: 'early-ming-village',
      text: '你帮里中长者搬运粮袋，换取一晚食宿。对方不问你太多，只问你是否愿意在里中登记为"客"。这是严法里最常见的生存方式——依附线在此收束。',
      choices: [
        {
          id: 'c_register',
          text: '接受登记，暂时依附此里',
          next: 'ending_success_belong',
          strategyTags: ['rely_on_relations', 'follow_institution'],
          settlementNote: '你接受里中登记，依附线达成容身。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: -15 }],
        },
        {
          id: 'c_refuse_register',
          text: '拒绝登记，连夜离开',
          next: 'ending_partial_flee',
          strategyTags: ['avoid_transfer'],
          settlementNote: '你拒绝登记连夜离开，暂脱险但未立足。',
          effects: [
            { type: 'modifyStat', stat: 'stamina', delta: -20 },
            { type: 'modifyStat', stat: 'exposure', delta: 10 },
          ],
        },
      ],
    },
    {
      id: 'ending_success_belong',
      type: 'ending',
      title: '暂得容身',
      outcome: 'success',
      text: '你在里中登记为客，暂时获得了可被当地承认的身份。严法之中，这已是难得的生存。',
      unlockSources: ['em_s1', 'em_s2'],
    },
    {
      id: 'ending_success_document',
      type: 'ending',
      title: '文书通行',
      outcome: 'success',
      text: '你凭封套通过盘查，并在下一处找到了可继续前行的道路。你仍不知未来几何，但至少没有被当场识破。',
      unlockSources: ['em_s2', 'em_s3'],
    },
    {
      id: 'ending_partial_flee',
      type: 'ending',
      title: '夜行脱险',
      outcome: 'partial',
      text: '你趁夜离开，躲过了当场查验，但饥饿与疲惫仍在累积。你活了下来，却仍未真正立足。',
      unlockSources: ['em_s3'],
    },
    {
      id: 'ending_exposed',
      type: 'ending',
      title: '来历败露',
      outcome: 'failure',
      text: '你的说法与时代细节对不上，吏员将你扣下问话。在缺少路引的情况下，这通常意味着失去自由行动的能力。',
      unlockSources: ['em_s2'],
    },
    {
      id: 'ending_exhaustion',
      type: 'ending',
      title: '力竭倒毙',
      outcome: 'failure',
      text: '你在道旁倒下，再未醒来。严法里，体力与粮食和路引一样，都是生存必需品。',
    },
    {
      id: 'ending_critical_injury',
      type: 'ending',
      title: '伤重不治',
      outcome: 'failure',
      text: '伤病耗尽了你最后一点行动能力。你未能走到下一个可以容身的地方。',
    },
    {
      id: 'ending_exposed_stat',
      type: 'ending',
      title: '嫌疑缠身',
      outcome: 'failure',
      text: '周围人对你的怀疑已到无法掩饰的地步。你已无法再以任何身份自如行动。',
    },
  ],
}
