import type { LevelPack } from '../../../game/types'

export const lateHanLevel: LevelPack = {
  id: 'late-han',
  title: '兖州道途',
  theme: 'late-han',
  eraLabel: '东汉末年',
  year: 190,
  regionLabel: '兖州',
  oneLiner: '你在官道边醒来，缺里证明，必须在盘查与依附之间找到活路。',
  coreCrisis: '缺里证明——没有乡里担保，你无法合法通行，随时可能被扣留问话。',
  historicalBackground:
    '公元190年前后，兖州地处中原要道，京师政局动荡，地方盘查趋严。汉代编户齐民制度要求行人持有乡里证明；战乱中大量人口流离，失去里籍者只能依附豪族、凭文书过关，或躲避查验。五铢钱仍流通，但粮价因战乱飞涨。这一关卡的危机，正是缺里证明者在乱世中求存的真实困境。',
  startNodeId: 'scene_awakening',
  correctAnswers: {
    period: '东汉末年',
    region: '兖州',
    identities: ['refugee', 'messenger', 'porter', 'tenant'],
  },
  sources: [
    {
      id: 'lh_s1',
      title: '后汉书·郡国志',
      citation: '《后汉书》卷二十八 郡国志',
      factType: 'historical',
      summary: '东汉末年州郡建制仍沿用州—郡—县层级，兖州为重要州域。',
      grade: 'A',
      author: '范晔',
      createdOrPublished: '445年',
      locator: '卷二十八 郡国志 兖州条',
      supports: '可证实东汉州—郡—县层级仍存，兖州辖陈留、东郡等属县，官称如"使君""明府"沿用汉制。',
      cannotProve: '无法证明190年某处聚落的具体盘查力度，亦不能据本条推断个人能否通行。',
    },
    {
      id: 'lh_s2',
      title: '睡虎地秦简与汉代户籍制度研究',
      citation: '学界关于汉代编户齐民与迁徙控制的综合研究',
      factType: 'inference',
      summary: '流民与过路者需依赖乡里担保或官方验视方可通行。',
      grade: 'B',
      author: '秦汉简牍学界',
      createdOrPublished: '20—21世纪',
      locator: '汉代编户齐民与迁徙控制相关章节',
      supports: '可推断无里籍者通行受限，需依附关系或官方文书作保；关隘验视符合制度逻辑。',
      cannotProve: '无法还原190年某一关隘的实际执行细节，亦不能证明所有聚落一律严查。',
    },
    {
      id: 'lh_s3',
      title: '汉代货币与物价',
      citation: '汉代五铢钱流通与地方物价记载',
      factType: 'historical',
      summary: '五铢钱仍是主要流通货币，粮价因战乱波动剧烈。',
      grade: 'B',
      author: '汉代经济史研究者',
      createdOrPublished: '汉代（文献成书年代不一）',
      locator: '五铢流通与粮价相关记载',
      supports: '可证实五铢仍为主要货币，战乱时期粮价远高于承平之年。',
      cannotProve: '无法给出190年某一聚落的精确粮价，亦不能据货币推断具体州境。',
    },
  ],
  identities: [
    {
      id: 'refugee',
      label: '逃离原籍的流民',
      description: '你失去了完整的乡里证明，只能依附他人或躲避查验。',
      background: {
        livelihood: '无固定生计，靠乞讨、帮工或拾遗过日',
        socialPosition: '编户之外的流民，不在任何里中正式登记',
        affiliation: '无所依附，或临时混在过路人群中',
        rightsAndLimits: '无权自由通行，不得请领官粮，易被扣留问话',
        exposureReason: '缺失乡里证明，无法应对关隘盘查',
      },
      sourceIds: ['lh_s2', 'lh_s1'],
      startingStats: { stamina: 55, wealth: 8, exposure: 25 },
      flags: ['no_hukou'],
    },
    {
      id: 'messenger',
      label: '传递文书的行人',
      description: '你携有封套，但并不知道其中内容是否仍被承认。',
      background: {
        livelihood: '以递送封套、传递消息为业',
        socialPosition: '低阶差遣人员，非正式朝廷命官',
        affiliation: '依附雇主或地方官府的临时任务',
        rightsAndLimits: '凭封套可有限通行，但需对答行文样式与去向',
        exposureReason: '封套若与吏员所识不符，或答不上细节，立刻暴露',
      },
      sourceIds: ['lh_s2', 'lh_s3'],
      startingStats: { stamina: 65, wealth: 15, exposure: 15 },
      flags: ['has_document'],
    },
    {
      id: 'porter',
      label: '随队赶路的脚夫',
      description: '你熟悉道路，却与雇主失散，需重新找到可依附的队伍。',
      background: {
        livelihood: '以肩挑背扛、随队运输为业',
        socialPosition: '依附商队或豪族的底层劳力',
        affiliation: '与雇主失散，暂无所属队伍',
        rightsAndLimits: '熟悉道路但不能独自过关，需雇主或里中作保',
        exposureReason: '独行脚夫身份可疑，缺少雇主信物或担保',
      },
      sourceIds: ['lh_s1', 'lh_s3'],
      startingStats: { stamina: 75, wealth: 12, exposure: 12 },
      flags: ['knows_road'],
    },
    {
      id: 'tenant',
      label: '依附地方豪族的佃客',
      description: '你原本属于某处田庄，战乱迫使你在外寻找旧主或新依附。',
      background: {
        livelihood: '耕作田庄，替豪族承役纳赋',
        socialPosition: '半人身依附的下级依附民，非自由编户',
        affiliation: '原属某处田庄，战火中与旧主失散',
        rightsAndLimits: '依附主家时可获庇护，但须承担役使与随调',
        exposureReason: '找不到旧主，无法证明现有依附关系',
      },
      sourceIds: ['lh_s1', 'lh_s2'],
      startingStats: { stamina: 60, wealth: 18, exposure: 10 },
      flags: ['has_patron_hint'],
    },
  ],
  evidence: [
    {
      id: 'lh_e1',
      title: '五铢钱与粮价',
      description: '道旁交易中仍使用五铢钱，但一石粮价远高于太平时期。',
      category: '货币与交易',
      strength: 'strong',
      sourceId: 'lh_s3',
      hints: { period: '东汉', region: '中原' },
    },
    {
      id: 'lh_e2',
      title: '州郡与县令称谓',
      description: '地方吏员仍称"使君""明府"，说明汉制官称尚未完全崩解。',
      category: '官制与法律',
      strength: 'strong',
      sourceId: 'lh_s1',
      hints: { period: '东汉末年' },
    },
    {
      id: 'lh_e3',
      title: '道路查验',
      description: '关隘处要求出示乡里证明或验视封套，无证明者不得随意通行。',
      category: '社会习俗',
      strength: 'strong',
      sourceId: 'lh_s2',
      hints: { identity: '需依附关系' },
    },
    {
      id: 'lh_e4',
      title: '道旁残碑',
      description: '残碑年号模糊，但"永"字可辨，似为东汉年号系统。',
      category: '文字与文书',
      strength: 'weak',
      sourceId: 'lh_s1',
      hints: { period: '东汉' },
    },
    {
      id: 'lh_e5',
      title: '逃难者口述',
      description: '有人说"黄巾余党已平"，又有人说"董公入京"，信息互相矛盾。',
      category: '语言与称谓',
      strength: 'misleading',
      sourceId: 'lh_s2',
      hints: { period: '东汉末年' },
    },
    {
      id: 'lh_e6',
      title: '道旁里程木',
      description: '官道旁里程标记指向陈留、东郡方向，表明此地为州境要道。',
      category: '交通与通信',
      strength: 'strong',
      sourceId: 'lh_s1',
      hints: { region: '中原州境' },
    },
  ],
  nodes: [
    {
      id: 'scene_awakening',
      type: 'scene',
      title: '道旁醒来',
      background: 'late-han-road',
      text: '你在尘土飞扬的官道边醒来。道旁有人以"使君""明府"相称，远处里程木指向诸县方向。你不知道自己为何在此，但腹中饥饿，必须尽快找到可容身之处。',
      revealEvidence: ['lh_e2', 'lh_e6'],
      choices: [
        {
          id: 'c_follow_traffic',
          text: '随人流向最近的聚落移动',
          next: 'scene_village_gate',
          strategyTags: ['avoid_transfer'],
          settlementNote: '你选择随人流移动，以最低暴露代价接近聚落。',
          effects: [{ type: 'modifyStat', stat: 'stamina', delta: -8 }],
        },
        {
          id: 'c_check_body',
          text: '先检查随身物品与衣物',
          next: 'scene_inventory',
          strategyTags: ['conceal_identity'],
          settlementNote: '你暂缓前行，先确认身上是否还有可用凭证。',
        },
      ],
    },
    {
      id: 'scene_inventory',
      type: 'scene',
      title: '随身之物',
      background: 'late-han-road',
      text: '你的衣料并不华丽，却也不像寻常农人。若你记得自己携带文书或雇主信物，或许还能换取通行；若没有，就必须依赖他人担保。',
      choices: [
        {
          id: 'c_has_doc',
          text: '检查是否有封套或信物',
          next: 'scene_village_gate',
          condition: { type: 'flag', flag: 'has_document' },
          strategyTags: ['follow_institution'],
          settlementNote: '你确认封套仍在，文书线由此展开。',
          effects: [{ type: 'revealEvidence', evidenceId: 'lh_e3' }],
        },
        {
          id: 'c_no_doc',
          text: '确认没有可用凭证，只能先找地方落脚',
          next: 'scene_village_gate',
          condition: { type: 'flag', flag: 'has_document', value: false },
          strategyTags: ['conceal_identity'],
          settlementNote: '你确认无凭证可用，只能以过路者身份试探。',
          effects: [
            { type: 'modifyStat', stat: 'exposure', delta: 5 },
            { type: 'revealEvidence', evidenceId: 'lh_e5' },
          ],
        },
      ],
    },
    {
      id: 'scene_village_gate',
      type: 'scene',
      title: '聚落外',
      background: 'late-han-village',
      text: '聚落外有人以五铢钱换粮，价格贵得惊人。守门者问你是哪里的"客"，有无里中证明。你意识到，在这里，来历比力气更重要。',
      revealEvidence: ['lh_e1', 'lh_e4'],
      choices: [
        {
          id: 'c_claim_traveler',
          text: '自称过路行人，请求借宿',
          next: 'scene_inn',
          strategyTags: ['conceal_identity'],
          settlementNote: '你以过路行人自称，换取进入聚落的机会。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 8 }],
        },
        {
          id: 'c_show_document',
          text: '出示封套，称有公务在身',
          next: 'scene_inn',
          condition: { type: 'flag', flag: 'has_document' },
          strategyTags: ['follow_institution'],
          settlementNote: '你出示封套，以公务行人身份降低怀疑。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: -5 }],
        },
        {
          id: 'c_find_patron',
          text: '打听是否有人认得你的旧主',
          next: 'scene_inn',
          condition: { type: 'flag', flag: 'has_patron_hint' },
          strategyTags: ['rely_on_relations'],
          settlementNote: '你沿依附线打听旧主下落，寻求豪族庇护。',
        },
        {
          id: 'c_porter_offer',
          text: '主动帮商队搬运粮袋，换一顿食',
          next: 'scene_porter_labor',
          condition: { type: 'flag', flag: 'knows_road' },
          strategyTags: ['labor_trade'],
          settlementNote: '你以劳力换取信任，脚夫劳动线由此展开。',
        },
      ],
    },
    {
      id: 'scene_inn',
      type: 'scene',
      title: '道旁酒肆',
      background: 'late-han-inn',
      speaker: '酒保',
      text: '酒保一边擦案一边打量你："近来道上不太平，无里证明者，最好莫乱说话。你若想往东，得先弄清是谁在盘查。"',
      revealEvidence: ['lh_e3'],
      choices: [
        {
          id: 'c_listen',
          text: '先听酒肆中人议论局势',
          next: 'scene_rumors',
          strategyTags: ['rely_on_relations'],
          settlementNote: '你从酒肆闲谈中获取局势碎片。',
          effects: [{ type: 'revealEvidence', evidenceId: 'lh_e5' }],
        },
        {
          id: 'c_buy_food',
          text: '用五铢钱买饼充饥',
          next: 'scene_rumors',
          strategyTags: ['exchange_resources'],
          settlementNote: '你花费五铢钱换得体力，继续收集线索。',
          effects: [
            { type: 'modifyStat', stat: 'wealth', delta: -5 },
            { type: 'modifyStat', stat: 'stamina', delta: 10 },
          ],
        },
      ],
    },
    {
      id: 'scene_rumors',
      type: 'scene',
      title: '传闻与线索',
      background: 'late-han-inn',
      text: '有人提及"京师有变"，也有人只说"里中催税比往年更急"。这些说法都不足以单独定年，但足以说明：你所在的不是太平岁月。你必须选择下一步的生存策略。',
      choices: [
        {
          id: 'c_submit_hypothesis',
          text: '整理线索，形成对年代与身份的判断',
          next: 'scene_decision',
          strategyTags: ['follow_institution'],
          settlementNote: '你整理已知线索，准备做出关键抉择。',
        },
        {
          id: 'c_refugee_hide',
          text: '趁夜离开酒肆，躲入道旁废弃仓窖',
          next: 'scene_refugee_hide',
          condition: { type: 'flag', flag: 'no_hukou' },
          strategyTags: ['conceal_identity', 'avoid_transfer'],
          settlementNote: '你选择躲避盘查，流民躲避线由此展开。',
        },
        {
          id: 'c_messenger_checkpoint',
          text: '向脚夫打听前方关隘，准备持封套过关',
          next: 'scene_checkpoint',
          condition: { type: 'flag', flag: 'has_document' },
          strategyTags: ['follow_institution'],
          settlementNote: '你沿文书线打听关隘，准备凭封套通行。',
        },
        {
          id: 'c_tenant_patron',
          text: '按旧主名号打听，寻里中长者引荐',
          next: 'scene_local_route',
          condition: { type: 'flag', flag: 'has_patron_hint' },
          strategyTags: ['rely_on_relations'],
          settlementNote: '你沿依附线寻找里中担保，直接求容身。',
        },
        {
          id: 'c_ask_checkpoint_any',
          text: '向酒保打听前方关隘情况',
          next: 'scene_checkpoint',
        },
      ],
    },
    {
      id: 'scene_checkpoint',
      type: 'scene',
      title: '关隘消息',
      background: 'late-han-road',
      text: '前方确有吏员验看行人。无里证明者会被扣留问话，携带封套者则需对得上封套样式与去向。脚夫们低声说，最近查得比往年更紧。',
      revealEvidence: ['lh_e3'],
      choices: [
        {
          id: 'c_to_decision',
          text: '带着这些消息回去整理判断',
          next: 'scene_decision',
          strategyTags: ['follow_institution'],
          settlementNote: '你掌握关隘情报，回到抉择节点。',
        },
      ],
    },
    {
      id: 'scene_refugee_hide',
      type: 'scene',
      title: '仓窖藏身',
      background: 'late-han-village',
      text: '你在废弃仓窖中缩着身子，远处传来更鼓与犬吠。没有里证明，你不敢走大路；但躲藏也意味着饥饿一日日加重。你必须决定是继续躲，还是冒险混入下一波过路人群。',
      choices: [
        {
          id: 'c_hide_flee',
          text: '趁夜沿田间小径离开，避开关隘',
          next: 'ending_partial_flee',
          strategyTags: ['avoid_transfer', 'conceal_identity'],
          settlementNote: '你沿小径夜行，躲过当场查验但尚未立足。',
          effects: [
            { type: 'modifyStat', stat: 'stamina', delta: -18 },
            { type: 'modifyStat', stat: 'exposure', delta: -8 },
          ],
        },
        {
          id: 'c_hide_blend',
          text: '混入过路人群，尝试重新进入聚落',
          next: 'scene_decision',
          strategyTags: ['conceal_identity'],
          settlementNote: '你冒险混入人群，暴露风险上升。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 12 }],
        },
        {
          id: 'c_hide_caught',
          text: '仓窖外有人举火查问，你应答失当',
          next: 'ending_exposed',
          condition: { type: 'hypothesisMismatch', field: 'period', value: '东汉末年' },
          strategyTags: ['conceal_identity'],
          settlementNote: '你应答露出破绽，被当场扣留问话。',
        },
      ],
    },
    {
      id: 'scene_porter_labor',
      type: 'scene',
      title: '以力换食',
      background: 'late-han-village',
      text: '你帮商队与里中长者搬运粮袋，换来一顿食与半日歇脚。对方不问你太多来历，只看你肯不肯出力。脚夫在乱世里，有时比文书更管用——但出力换不来里籍，只能换一时信任。',
      choices: [
        {
          id: 'c_labor_register',
          text: '继续出力，请求在里中登记为"客"',
          next: 'ending_success_belong',
          strategyTags: ['labor_trade', 'rely_on_relations'],
          settlementNote: '你以劳动换取里中登记，暂获容身。',
          effects: [
            { type: 'modifyStat', stat: 'stamina', delta: -10 },
            { type: 'modifyStat', stat: 'exposure', delta: -12 },
          ],
        },
        {
          id: 'c_labor_move_on',
          text: '歇脚后继续随商队东行',
          next: 'scene_decision',
          strategyTags: ['labor_trade'],
          settlementNote: '你随商队继续前行，劳动线汇入抉择节点。',
          effects: [{ type: 'modifyStat', stat: 'stamina', delta: 5 }],
        },
      ],
    },
    {
      id: 'scene_decision',
      type: 'scene',
      title: '抉择',
      background: 'late-han-road',
      text: '你必须决定：是继续向东依附大城，还是留在地方寻找可容身的乡里关系。若你对年代和身份判断有误，错误自称会立刻引来怀疑。',
      choices: [
        {
          id: 'c_east_official',
          text: '自称汉室属吏，请求官方保护',
          next: 'scene_east_route',
          requiresCorrectHypothesis: 'period',
          strategyTags: ['follow_institution'],
          settlementNote: '你以官方身份自称，冒了暴露风险。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 15 }],
        },
        {
          id: 'c_local_hide',
          text: '留在地方，先找里中担保再行动',
          next: 'scene_local_route',
          strategyTags: ['rely_on_relations'],
          settlementNote: '你选择依附乡里，寻求里中担保。',
          effects: [{ type: 'modifyStat', stat: 'stamina', delta: -5 }],
        },
        {
          id: 'c_use_document',
          text: '持封套过卡，按文书路线前进',
          next: 'scene_document_route',
          condition: { type: 'flag', flag: 'has_document' },
          requiresCorrectHypothesis: 'identity',
          strategyTags: ['follow_institution'],
          settlementNote: '你持封套过关，文书线进入最后阶段。',
        },
      ],
    },
    {
      id: 'scene_east_route',
      type: 'scene',
      title: '东行',
      background: 'late-han-road',
      text: '你以不符时宜的自称应对盘查，吏员越听越疑。若你其实不了解当前官制细节，这一步几乎等于自证可疑。',
      choices: [
        {
          id: 'c_exposed',
          text: '强行继续东行',
          next: 'ending_exposed',
          condition: { type: 'hypothesisMismatch', field: 'period', value: '东汉末年' },
          strategyTags: ['follow_institution'],
          settlementNote: '你强行东行，因年代判断错误而暴露。',
        },
        {
          id: 'c_recover',
          text: '改口称过路行人，请求暂留',
          next: 'scene_local_route',
          strategyTags: ['conceal_identity'],
          settlementNote: '你改口称过路行人，退回依附路线。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 10 }],
        },
      ],
    },
    {
      id: 'scene_document_route',
      type: 'scene',
      title: '持封套前行',
      background: 'late-han-road',
      text: '封套样式与吏员所识相符，你得以通过关隘。但若你并不真正理解文书所代表的职责，前方仍可能因答不上细节而暴露。',
      choices: [
        {
          id: 'c_success_doc',
          text: '按封套指示前往下一处',
          next: 'ending_success_document',
          condition: { type: 'hypothesisMatch', field: 'period', value: '东汉末年' },
          strategyTags: ['follow_institution'],
          settlementNote: '你凭封套通过盘查，文书线达成通行。',
        },
        {
          id: 'c_fail_doc',
          text: '继续冒名前行',
          next: 'ending_exposed',
          condition: { type: 'hypothesisMismatch', field: 'period', value: '东汉末年' },
          strategyTags: ['conceal_identity'],
          settlementNote: '你冒名前行，因判断失误而被识破。',
        },
      ],
    },
    {
      id: 'scene_local_route',
      type: 'scene',
      title: '乡里依附',
      background: 'late-han-village',
      text: '你帮里中长者搬运粮袋，换取一晚食宿。对方不问你太多，只问你是否愿意在里中登记为"客"。这是乱世里最常见的生存方式——依附线在此收束。',
      choices: [
        {
          id: 'c_register',
          text: '接受登记，暂时依附此里',
          next: 'ending_success_belong',
          strategyTags: ['rely_on_relations', 'follow_institution'],
          settlementNote: '你接受里中登记，依附线达成容身。',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: -15 }],
        },
        {
          id: 'c_refuse_register',
          text: '拒绝登记，连夜离开',
          next: 'ending_partial_flee',
          strategyTags: ['avoid_transfer'],
          settlementNote: '你拒绝登记连夜离开，暂脱险但未立足。',
          effects: [
            { type: 'modifyStat', stat: 'stamina', delta: -20 },
            { type: 'modifyStat', stat: 'exposure', delta: 10 },
          ],
        },
      ],
    },
    {
      id: 'ending_success_belong',
      type: 'ending',
      title: '暂得容身',
      outcome: 'success',
      text: '你在里中登记为客，暂时获得了可被当地承认的身份。乱世之中，这已是难得的生存。',
      unlockSources: ['lh_s1', 'lh_s2'],
    },
    {
      id: 'ending_success_document',
      type: 'ending',
      title: '文书通行',
      outcome: 'success',
      text: '你凭封套通过盘查，并在下一处找到了可继续前行的道路。你仍不知未来几何，但至少没有被当场识破。',
      unlockSources: ['lh_s2', 'lh_s3'],
    },
    {
      id: 'ending_partial_flee',
      type: 'ending',
      title: '夜行脱险',
      outcome: 'partial',
      text: '你趁夜离开，躲过了当场查验，但饥饿与疲惫仍在累积。你活了下来，却仍未真正立足。',
      unlockSources: ['lh_s3'],
    },
    {
      id: 'ending_exposed',
      type: 'ending',
      title: '来历败露',
      outcome: 'failure',
      text: '你的说法与时代细节对不上，吏员将你扣下问话。在缺少乡里证明的情况下，这通常意味着失去自由行动的能力。',
      unlockSources: ['lh_s2'],
    },
    {
      id: 'ending_exhaustion',
      type: 'ending',
      title: '力竭倒毙',
      outcome: 'failure',
      text: '你在道旁倒下，再未醒来。乱世里，体力与粮食和身份一样，都是生存必需品。',
    },
    {
      id: 'ending_critical_injury',
      type: 'ending',
      title: '伤重不治',
      outcome: 'failure',
      text: '伤病耗尽了你最后一点行动能力。你未能走到下一个可以容身的地方。',
    },
    {
      id: 'ending_exposed_stat',
      type: 'ending',
      title: '嫌疑缠身',
      outcome: 'failure',
      text: '周围人对你的怀疑已到无法掩饰的地步。你已无法再以任何身份自如行动。',
    },
  ],
}
