import type { LevelPack } from '../../../game/types'

export const lateHanLevel: LevelPack = {
  id: 'late-han',
  title: '兖州道途',
  theme: 'late-han',
  eraLabel: '东汉末年',
  year: 190,
  regionLabel: '兖州',
  startNodeId: 'scene_awakening',
  correctAnswers: {
    period: '东汉末年',
    region: '兖州',
    identities: ['refugee', 'messenger', 'porter', 'tenant'],
  },
  sources: [
    {
      id: 'lh_s1',
      title: '后汉书·郡国志',
      citation: '《后汉书》卷二十八 郡国志',
      factType: 'historical',
      summary: '东汉末年州郡建制仍沿用州—郡—县层级，兖州为重要州域。',
    },
    {
      id: 'lh_s2',
      title: '睡虎地秦简与汉代户籍制度研究',
      citation: '学界关于汉代编户齐民与迁徙控制的综合研究',
      factType: 'inference',
      summary: '流民与过路者需依赖乡里担保或官方验视方可通行。',
    },
    {
      id: 'lh_s3',
      title: '汉代货币与物价',
      citation: '汉代五铢钱流通与地方物价记载',
      factType: 'historical',
      summary: '五铢钱仍是主要流通货币，粮价因战乱波动剧烈。',
    },
  ],
  identities: [
    {
      id: 'refugee',
      label: '逃离原籍的流民',
      description: '你失去了完整的乡里证明，只能依附他人或躲避查验。',
      startingStats: { stamina: 55, wealth: 8, exposure: 25 },
      flags: ['no_hukou'],
    },
    {
      id: 'messenger',
      label: '传递文书的行人',
      description: '你携有封套，但并不知道其中内容是否仍被承认。',
      startingStats: { stamina: 65, wealth: 15, exposure: 15 },
      flags: ['has_document'],
    },
    {
      id: 'porter',
      label: '随队赶路的脚夫',
      description: '你熟悉道路，却与雇主失散，需重新找到可依附的队伍。',
      startingStats: { stamina: 75, wealth: 12, exposure: 12 },
      flags: ['knows_road'],
    },
    {
      id: 'tenant',
      label: '依附地方豪族的佃客',
      description: '你原本属于某处田庄，战乱迫使你在外寻找旧主或新依附。',
      startingStats: { stamina: 60, wealth: 18, exposure: 10 },
      flags: ['has_patron_hint'],
    },
  ],
  evidence: [
    {
      id: 'lh_e1',
      title: '五铢钱与粮价',
      description: '道旁交易中仍使用五铢钱，但一石粮价远高于太平时期。',
      category: '货币与交易',
      strength: 'strong',
      sourceId: 'lh_s3',
      hints: { period: '东汉', region: '中原' },
    },
    {
      id: 'lh_e2',
      title: '州郡与县令称谓',
      description: '地方吏员仍称“使君”“明府”，说明汉制官称尚未完全崩解。',
      category: '官制与法律',
      strength: 'strong',
      sourceId: 'lh_s1',
      hints: { period: '东汉末年' },
    },
    {
      id: 'lh_e3',
      title: '道路查验',
      description: '关隘处要求出示乡里证明或验视封套，无证明者不得随意通行。',
      category: '社会习俗',
      strength: 'strong',
      sourceId: 'lh_s2',
      hints: { identity: '需依附关系' },
    },
    {
      id: 'lh_e4',
      title: '道旁残碑',
      description: '残碑年号模糊，但“永”字可辨，似为东汉年号系统。',
      category: '文字与文书',
      strength: 'weak',
      sourceId: 'lh_s1',
      hints: { period: '东汉' },
    },
    {
      id: 'lh_e5',
      title: '逃难者口述',
      description: '有人说“黄巾余党已平”，又有人说“董公入京”，信息互相矛盾。',
      category: '语言与称谓',
      strength: 'misleading',
      sourceId: 'lh_s2',
      hints: { period: '东汉末年' },
    },
    {
      id: 'lh_e6',
      title: '兖州道里程',
      description: '道旁里程标记指向陈留、东郡方向，表明你位于兖州境内。',
      category: '交通与通信',
      strength: 'strong',
      sourceId: 'lh_s1',
      hints: { region: '兖州' },
    },
  ],
  nodes: [
    {
      id: 'scene_awakening',
      type: 'scene',
      title: '道旁醒来',
      background: 'late-han-road',
      text: '你在尘土飞扬的官道边醒来。道旁有人以“使君”“明府”相称，远处里程木指向兖州诸县。你不知道自己为何在此，但腹中饥饿，必须尽快找到可容身之处。',
      revealEvidence: ['lh_e2', 'lh_e6'],
      choices: [
        {
          id: 'c_follow_traffic',
          text: '随人流向最近的聚落移动',
          next: 'scene_village_gate',
          effects: [{ type: 'modifyStat', stat: 'stamina', delta: -8 }],
        },
        {
          id: 'c_check_body',
          text: '先检查随身物品与衣物',
          next: 'scene_inventory',
        },
      ],
    },
    {
      id: 'scene_inventory',
      type: 'scene',
      title: '随身之物',
      background: 'late-han-road',
      text: '你的衣料并不华丽，却也不像寻常农人。若你记得自己携带文书或雇主信物，或许还能换取通行；若没有，就必须依赖他人担保。',
      choices: [
        {
          id: 'c_has_doc',
          text: '检查是否有封套或信物',
          next: 'scene_village_gate',
          condition: { type: 'flag', flag: 'has_document' },
          effects: [{ type: 'revealEvidence', evidenceId: 'lh_e3' }],
        },
        {
          id: 'c_no_doc',
          text: '确认没有可用凭证，只能先找地方落脚',
          next: 'scene_village_gate',
          condition: { type: 'flag', flag: 'has_document', value: false },
          effects: [
            { type: 'modifyStat', stat: 'exposure', delta: 5 },
            { type: 'revealEvidence', evidenceId: 'lh_e5' },
          ],
        },
      ],
    },
    {
      id: 'scene_village_gate',
      type: 'scene',
      title: '聚落外',
      background: 'late-han-village',
      text: '聚落外有人以五铢钱换粮，价格贵得惊人。守门者问你是哪里的“客”，有无里中证明。你意识到，在这里，来历比力气更重要。',
      revealEvidence: ['lh_e1', 'lh_e4'],
      choices: [
        {
          id: 'c_claim_traveler',
          text: '自称过路行人，请求借宿',
          next: 'scene_inn',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 8 }],
        },
        {
          id: 'c_show_document',
          text: '出示封套，称有公务在身',
          next: 'scene_inn',
          condition: { type: 'flag', flag: 'has_document' },
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: -5 }],
        },
        {
          id: 'c_find_patron',
          text: '打听是否有人认得你的旧主',
          next: 'scene_inn',
          condition: { type: 'flag', flag: 'has_patron_hint' },
        },
      ],
    },
    {
      id: 'scene_inn',
      type: 'scene',
      title: '道旁酒肆',
      background: 'late-han-inn',
      speaker: '酒保',
      text: '酒保一边擦案一边打量你：“近来兖州道上不太平，无里证明者，最好莫乱说话。你若想往东，得先弄清是谁在盘查。”',
      revealEvidence: ['lh_e3'],
      choices: [
        {
          id: 'c_listen',
          text: '先听酒肆中人议论局势',
          next: 'scene_rumors',
          effects: [{ type: 'revealEvidence', evidenceId: 'lh_e5' }],
        },
        {
          id: 'c_buy_food',
          text: '用五铢钱买饼充饥',
          next: 'scene_rumors',
          effects: [
            { type: 'modifyStat', stat: 'wealth', delta: -5 },
            { type: 'modifyStat', stat: 'stamina', delta: 10 },
          ],
        },
      ],
    },
    {
      id: 'scene_rumors',
      type: 'scene',
      title: '传闻与线索',
      background: 'late-han-inn',
      text: '有人提及“京师有变”，也有人只说“里中催税比往年更急”。这些说法都不足以单独定年，但足以说明：你所在的不是太平岁月。',
      choices: [
        {
          id: 'c_submit_hypothesis',
          text: '整理线索，形成对年代与身份的判断',
          next: 'scene_decision',
        },
        {
          id: 'c_ask_checkpoint',
          text: '向脚夫打听前方关隘情况',
          next: 'scene_checkpoint',
          condition: { type: 'flag', flag: 'knows_road' },
        },
        {
          id: 'c_ask_checkpoint_any',
          text: '向酒保打听前方关隘情况',
          next: 'scene_checkpoint',
        },
      ],
    },
    {
      id: 'scene_checkpoint',
      type: 'scene',
      title: '关隘消息',
      background: 'late-han-road',
      text: '前方确有吏员验看行人。无里证明者会被扣留问话，携带封套者则需对得上封套样式与去向。',
      revealEvidence: ['lh_e3'],
      choices: [
        {
          id: 'c_to_decision',
          text: '带着这些消息回去整理判断',
          next: 'scene_decision',
        },
      ],
    },
    {
      id: 'scene_decision',
      type: 'scene',
      title: '抉择',
      background: 'late-han-road',
      text: '你必须决定：是继续向东依附大城，还是留在地方寻找可容身的乡里关系。若你对年代和身份判断有误，错误自称会立刻引来怀疑。',
      choices: [
        {
          id: 'c_east_official',
          text: '自称汉室属吏，请求官方保护',
          next: 'scene_east_route',
          requiresCorrectHypothesis: 'period',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 15 }],
        },
        {
          id: 'c_local_hide',
          text: '留在地方，先找里中担保再行动',
          next: 'scene_local_route',
          effects: [{ type: 'modifyStat', stat: 'stamina', delta: -5 }],
        },
        {
          id: 'c_use_document',
          text: '持封套过卡，按文书路线前进',
          next: 'scene_document_route',
          condition: { type: 'flag', flag: 'has_document' },
          requiresCorrectHypothesis: 'identity',
        },
      ],
    },
    {
      id: 'scene_east_route',
      type: 'scene',
      title: '东行',
      background: 'late-han-road',
      text: '你以不符时宜的自称应对盘查，吏员越听越疑。若你其实不了解当前官制细节，这一步几乎等于自证可疑。',
      choices: [
        {
          id: 'c_exposed',
          text: '强行继续东行',
          next: 'ending_exposed',
          condition: { type: 'hypothesisMismatch', field: 'period', value: '东汉末年' },
        },
        {
          id: 'c_recover',
          text: '改口称过路行人，请求暂留',
          next: 'scene_local_route',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: 10 }],
        },
      ],
    },
    {
      id: 'scene_document_route',
      type: 'scene',
      title: '持封套前行',
      background: 'late-han-road',
      text: '封套样式与吏员所识相符，你得以通过关隘。但若你并不真正理解文书所代表的职责，前方仍可能因答不上细节而暴露。',
      choices: [
        {
          id: 'c_success_doc',
          text: '按封套指示前往下一处',
          next: 'ending_success_document',
          condition: { type: 'hypothesisMatch', field: 'period', value: '东汉末年' },
        },
        {
          id: 'c_fail_doc',
          text: '继续冒名前行',
          next: 'ending_exposed',
          condition: { type: 'hypothesisMismatch', field: 'period', value: '东汉末年' },
        },
      ],
    },
    {
      id: 'scene_local_route',
      type: 'scene',
      title: '乡里依附',
      background: 'late-han-village',
      text: '你帮里中长者搬运粮袋，换取一晚食宿。对方不问你太多，只问你是否愿意在里中登记为“客”。这是乱世里最常见的生存方式。',
      choices: [
        {
          id: 'c_register',
          text: '接受登记，暂时依附此里',
          next: 'ending_success_belong',
          effects: [{ type: 'modifyStat', stat: 'exposure', delta: -15 }],
        },
        {
          id: 'c_refuse_register',
          text: '拒绝登记，连夜离开',
          next: 'ending_partial_flee',
          effects: [
            { type: 'modifyStat', stat: 'stamina', delta: -20 },
            { type: 'modifyStat', stat: 'exposure', delta: 10 },
          ],
        },
      ],
    },
    {
      id: 'ending_success_belong',
      type: 'ending',
      title: '暂得容身',
      outcome: 'success',
      text: '你在里中登记为客，暂时获得了可被当地承认的身份。乱世之中，这已是难得的生存。',
      unlockSources: ['lh_s1', 'lh_s2'],
    },
    {
      id: 'ending_success_document',
      type: 'ending',
      title: '文书通行',
      outcome: 'success',
      text: '你凭封套通过盘查，并在下一处找到了可继续前行的道路。你仍不知未来几何，但至少没有被当场识破。',
      unlockSources: ['lh_s2', 'lh_s3'],
    },
    {
      id: 'ending_partial_flee',
      type: 'ending',
      title: '夜行脱险',
      outcome: 'partial',
      text: '你趁夜离开，躲过了当场查验，但饥饿与疲惫仍在累积。你活了下来，却仍未真正立足。',
      unlockSources: ['lh_s3'],
    },
    {
      id: 'ending_exposed',
      type: 'ending',
      title: '来历败露',
      outcome: 'failure',
      text: '你的说法与时代细节对不上，吏员将你扣下问话。在缺少乡里证明的情况下，这通常意味着失去自由行动的能力。',
      unlockSources: ['lh_s2'],
    },
    {
      id: 'ending_exhaustion',
      type: 'ending',
      title: '力竭倒毙',
      outcome: 'failure',
      text: '你在道旁倒下，再未醒来。乱世里，体力与粮食和身份一样，都是生存必需品。',
    },
    {
      id: 'ending_critical_injury',
      type: 'ending',
      title: '伤重不治',
      outcome: 'failure',
      text: '伤病耗尽了你最后一点行动能力。你未能走到下一个可以容身的地方。',
    },
    {
      id: 'ending_exposed_stat',
      type: 'ending',
      title: '嫌疑缠身',
      outcome: 'failure',
      text: '周围人对你的怀疑已到无法掩饰的地步。你已无法再以任何身份自如行动。',
    },
  ],
}
